package codexhx.runtime.tui.resume;

typedef ResumePickerCommandFields = {
	final kind:ResumePickerCommandKind;
	final action:ResumePickerActionKind;
	final keyName:String;
	final threadId:String;
	final pendingThreadId:String;
	final expandedThreadId:String;
	final targetPath:String;
	final targetLabel:String;
	final errorMessage:String;
	final failureCode:String;
	final query:String;
	final queryBefore:String;
	final queryAfter:String;
	final cursor:String;
	final nextCursor:String;
	final sortKey:ResumePickerSortKey;
	final sortKeyBefore:ResumePickerSortKey;
	final sortKeyAfter:ResumePickerSortKey;
	final filterModeBefore:ResumePickerFilterMode;
	final filterModeAfter:ResumePickerFilterMode;
	final densityBefore:ResumePickerDensity;
	final densityAfter:ResumePickerDensity;
	final toolbarFocusBefore:ResumePickerToolbarFocus;
	final toolbarFocusAfter:ResumePickerToolbarFocus;
	final toolbarRenderMode:String;
	final previewState:String;
	final previewCacheAfter:String;
	final transcriptState:String;
	final transcriptCacheAfter:String;
	final footerProgressLabel:String;
	final footerHintMode:String;
	final emptyStateMessage:String;
	final loadingOverlayMessage:String;
	final cwdFilter:String;
	final requestToken:Int;
	final searchToken:Int;
	final scannedRows:Int;
	final acceptedRows:Int;
	final invalidRows:Int;
	final loadedRows:Int;
	final filteredRows:Int;
	final selectedIndex:Int;
	final selectedBefore:Int;
	final selectedAfter:Int;
	final scrollTopBefore:Int;
	final scrollTopAfter:Int;
	final viewRows:Int;
	final pageSize:Int;
	final footerPercent:Int;
	final frozenFooterPercent:Int;
	final footerWidth:Int;
	final previewLineCount:Int;
	final userLineCount:Int;
	final assistantLineCount:Int;
	final transcriptCellCount:Int;
	final planCellCount:Int;
	final reasoningCellCount:Int;
	final fallbackCellCount:Int;
	final showAll:Bool;
	final includeNonInteractive:Bool;
	final remoteWorkspace:Bool;
	final altScreenEntered:Bool;
	final altScreenExited:Bool;
	final searchActive:Bool;
	final staleIgnored:Bool;
	final nextCursorPresent:Bool;
	final reachedScanCap:Bool;
	final pendingPageDownCompleted:Bool;
	final lookupRequested:Bool;
	final cacheInserted:Bool;
	final expansionToggled:Bool;
	final includeTurns:Bool;
	final threadReadRequested:Bool;
	final appServerStarted:Bool;
	final noModelCall:Bool;
	final noFilesystemMutation:Bool;
	final previewRendered:Bool;
	final selected:Bool;
	final loadingFrameShown:Bool;
	final overlayOpened:Bool;
	final loadMoreRequested:Bool;
	final startFresh:Bool;
	final keyConsumed:Bool;
	final overlayClosed:Bool;
	final persistenceConfigured:Bool;
	final persistenceAttempted:Bool;
	final persistenceSucceeded:Bool;
	final inlineErrorShown:Bool;
	final queryPreserved:Bool;
	final frameScheduled:Bool;
	final loadingPending:Bool;
	final moreAbove:Bool;
	final moreBelow:Bool;
	final loadingOlderShown:Bool;
	final compactFallback:Bool;
	final keyOnlyFallback:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class ResumePickerCommand {
	@:recordDefault(ResumePickerCommandKind.Unknown)
	public final kind:ResumePickerCommandKind;
	@:recordDefault(ResumePickerActionKind.Unknown)
	public final action:ResumePickerActionKind;
	public final keyName:String;
	public final threadId:String;
	public final pendingThreadId:String;
	public final expandedThreadId:String;
	public final targetPath:String;
	public final targetLabel:String;
	public final errorMessage:String;
	public final failureCode:String;
	public final query:String;
	public final queryBefore:String;
	public final queryAfter:String;
	public final cursor:String;
	public final nextCursor:String;
	@:recordDefault(ResumePickerSortKey.Unknown)
	public final sortKey:ResumePickerSortKey;
	@:recordDefault(ResumePickerSortKey.Unknown)
	public final sortKeyBefore:ResumePickerSortKey;
	@:recordDefault(ResumePickerSortKey.Unknown)
	public final sortKeyAfter:ResumePickerSortKey;
	@:recordDefault(ResumePickerFilterMode.Unknown)
	public final filterModeBefore:ResumePickerFilterMode;
	@:recordDefault(ResumePickerFilterMode.Unknown)
	public final filterModeAfter:ResumePickerFilterMode;
	@:recordDefault(ResumePickerDensity.Unknown)
	public final densityBefore:ResumePickerDensity;
	@:recordDefault(ResumePickerDensity.Unknown)
	public final densityAfter:ResumePickerDensity;
	@:recordDefault(ResumePickerToolbarFocus.Unknown)
	public final toolbarFocusBefore:ResumePickerToolbarFocus;
	@:recordDefault(ResumePickerToolbarFocus.Unknown)
	public final toolbarFocusAfter:ResumePickerToolbarFocus;
	public final toolbarRenderMode:String;
	public final previewState:String;
	public final previewCacheAfter:String;
	public final transcriptState:String;
	public final transcriptCacheAfter:String;
	public final footerProgressLabel:String;
	public final footerHintMode:String;
	public final emptyStateMessage:String;
	public final loadingOverlayMessage:String;
	public final cwdFilter:String;
	public final requestToken:Int;
	public final searchToken:Int;
	public final scannedRows:Int;
	public final acceptedRows:Int;
	public final invalidRows:Int;
	public final loadedRows:Int;
	public final filteredRows:Int;
	public final selectedIndex:Int;
	public final selectedBefore:Int;
	public final selectedAfter:Int;
	public final scrollTopBefore:Int;
	public final scrollTopAfter:Int;
	public final viewRows:Int;
	public final pageSize:Int;
	public final footerPercent:Int;
	public final frozenFooterPercent:Int;
	public final footerWidth:Int;
	public final previewLineCount:Int;
	public final userLineCount:Int;
	public final assistantLineCount:Int;
	public final transcriptCellCount:Int;
	public final planCellCount:Int;
	public final reasoningCellCount:Int;
	public final fallbackCellCount:Int;
	public final showAll:Bool;
	public final includeNonInteractive:Bool;
	public final remoteWorkspace:Bool;
	public final altScreenEntered:Bool;
	public final altScreenExited:Bool;
	public final searchActive:Bool;
	public final staleIgnored:Bool;
	public final nextCursorPresent:Bool;
	public final reachedScanCap:Bool;
	public final pendingPageDownCompleted:Bool;
	public final lookupRequested:Bool;
	public final cacheInserted:Bool;
	public final expansionToggled:Bool;
	public final includeTurns:Bool;
	public final threadReadRequested:Bool;
	public final appServerStarted:Bool;
	public final noModelCall:Bool;
	public final noFilesystemMutation:Bool;
	public final previewRendered:Bool;
	public final selected:Bool;
	public final loadingFrameShown:Bool;
	public final overlayOpened:Bool;
	public final loadMoreRequested:Bool;
	public final startFresh:Bool;
	public final keyConsumed:Bool;
	public final overlayClosed:Bool;
	public final persistenceConfigured:Bool;
	public final persistenceAttempted:Bool;
	public final persistenceSucceeded:Bool;
	public final inlineErrorShown:Bool;
	public final queryPreserved:Bool;
	public final frameScheduled:Bool;
	public final loadingPending:Bool;
	public final moreAbove:Bool;
	public final moreBelow:Bool;
	public final loadingOlderShown:Bool;
	public final compactFallback:Bool;
	public final keyOnlyFallback:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final unsupportedRejected:Bool;
}
