package codexhx.validation.tui.resume.live;

import codexhx.runtime.diagnostics.DiagnosticSummary;
import codexhx.runtime.tui.resume.host.RecoveryReplayAwareKeyboardReadiness;
import codexhx.runtime.tui.resume.host.RecoveryKeyboardIntentKind;

class NinthKeyboardReadinessGate {
	public static function run():NinthKeyboardReadinessReport {
		final handoffReport = EighthExecutionHandoffGate.run();
		final policy = new NinthKeyboardReadinessPolicy();
		final readiness = policy.admit(handoffReport, [RecoveryKeyboardIntentKind.MoveDown, RecoveryKeyboardIntentKind.MoveUp]);
		return new NinthKeyboardReadinessReport({
			readinessKind: readiness.kind,
			readinessSummary: compactReadinessSummary(readiness),
			decisionCount: readiness.decisionCount,
			admittedCount: readiness.admittedCount,
			postRenderIdleListReady: readiness.postRenderIdleListReady,
			keyboardInputReady: readiness.keyboardInputReady,
			listNavigationReady: readiness.listNavigationReady,
			recoveredSelectionStableUntilNavigation: readiness.recoveredSelectionStableUntilNavigation,
			navigationApplied: readiness.navigationApplied,
			returnedToRecoveredSelection: readiness.returnedToRecoveredSelection,
			noLeftoverScheduledRenderRequest: readiness.noLeftoverScheduledRenderRequest,
			sourceSchedulerRequestCount: readiness.sourceSchedulerRequestCount,
			consumedScheduledRequestCount: readiness.consumedScheduledRequestCount,
			renderCount: readiness.renderCount,
			renderedSnapshotPreserved: readiness.renderedSnapshotPreserved,
			finalThreadId: readiness.finalThreadId,
			finalFooter: readiness.finalFooter,
			finalSelectionPreserved: readiness.finalSelectionPreserved,
			finalFooterPreserved: readiness.finalFooterPreserved,
			inputAdmitted: readiness.inputAdmitted,
			localOnlyRenderIntent: readiness.localOnlyRenderIntent,
			completionReady: handoffReport.completionReady,
			nextSliceReady: handoffReport.nextSliceReady,
			replayCount: readiness.replayCount,
			sourceReplayCount: handoffReport.sourceReplayCount,
			sourceHandoffReplayCount: handoffReport.sourceHandoffReplayCount,
			sourceHandoffReadinessDecisionCount: handoffReport.sourceHandoffReadinessDecisionCount,
			sourceHandoffRenderStateCount: handoffReport.sourceHandoffRenderStateCount,
			sourceHandoffFrameRequests: handoffReport.sourceHandoffFrameRequests,
			sourceHandoffKeyboardRenderCount: handoffReport.sourceHandoffKeyboardRenderCount,
			sourceSecondCycleHandoffReplayCount: handoffReport.sourceSecondCycleHandoffReplayCount,
			sourceSecondCycleHandoffReadinessDecisionCount: handoffReport.sourceSecondCycleHandoffReadinessDecisionCount,
			sourceSecondCycleHandoffRenderStateCount: handoffReport.sourceSecondCycleHandoffRenderStateCount,
			sourceSecondCycleHandoffFrameRequests: handoffReport.sourceSecondCycleHandoffFrameRequests,
			sourceSecondCycleHandoffKeyboardRenderCount: handoffReport.sourceSecondCycleHandoffKeyboardRenderCount,
			sourceThirdCycleHandoffReplayCount: handoffReport.sourceThirdCycleHandoffReplayCount,
			sourceThirdCycleHandoffReadinessDecisionCount: handoffReport.sourceThirdCycleHandoffReadinessDecisionCount,
			sourceThirdCycleHandoffRenderStateCount: handoffReport.sourceThirdCycleHandoffRenderStateCount,
			sourceThirdCycleHandoffFrameRequests: handoffReport.sourceThirdCycleHandoffFrameRequests,
			sourceThirdCycleHandoffKeyboardRenderCount: handoffReport.sourceThirdCycleHandoffKeyboardRenderCount,
			sourceReadinessDecisionCount: handoffReport.sourceReadinessDecisionCount,
			sourceRenderStateCount: handoffReport.sourceRenderStateCount,
			sourceFrameRequests: handoffReport.sourceFrameRequests,
			sourceKeyboardRenderCount: handoffReport.sourceKeyboardRenderCount,
			snapshotOrderPreserved: readiness.snapshotOrderPreserved,
			selectedMarkersPreserved: readiness.selectedMarkersPreserved,
			footerSummariesPreserved: readiness.footerSummariesPreserved,
			selectedMarkerMoved: readiness.selectedMarkerMoved,
			recoveredSelectionRestored: readiness.recoveredSelectionRestored,
			sourcePreExecutionSchedulerRequestCount: readiness.sourcePreExecutionSchedulerRequestCount,
			sourcePreExecutionConsumedRequestCount: readiness.sourcePreExecutionConsumedRequestCount,
			sourcePreExecutionRenderCount: readiness.sourcePreExecutionRenderCount,
			sourceRenderedSnapshotPreserved: readiness.sourceRenderedSnapshotPreserved,
			sourceInputAdmitted: handoffReport.sourceInputAdmitted,
			sourceLocalOnlyRenderIntent: handoffReport.sourceLocalOnlyRenderIntent,
			sourceHandoffInputAdmitted: handoffReport.sourceHandoffInputAdmitted,
			sourceHandoffLocalOnlyRenderIntent: handoffReport.sourceHandoffLocalOnlyRenderIntent,
			sourceSecondCycleHandoffInputAdmitted: handoffReport.sourceSecondCycleHandoffInputAdmitted,
			sourceSecondCycleHandoffLocalOnlyRenderIntent: handoffReport.sourceSecondCycleHandoffLocalOnlyRenderIntent,
			sourceThirdCycleHandoffInputAdmitted: handoffReport.sourceThirdCycleHandoffInputAdmitted,
			sourceThirdCycleHandoffLocalOnlyRenderIntent: handoffReport.sourceThirdCycleHandoffLocalOnlyRenderIntent,
			sourceFourthCycleHandoffInputAdmitted: handoffReport.sourceFourthCycleHandoffInputAdmitted,
			sourceFourthCycleHandoffLocalOnlyRenderIntent: handoffReport.sourceFourthCycleHandoffLocalOnlyRenderIntent,
			stalePromptActionInactive: readiness.stalePromptActionInactive,
			staleSideParentActionInactive: readiness.staleSideParentActionInactive,
			staleActiveThreadActionInactive: readiness.staleActiveThreadActionInactive,
			ignoredNoSurfaceRecordsAbsent: readiness.ignoredNoSurfaceRecordsAbsent,
			noPressureDropRejection: readiness.noPressureDropRejection,
			liveTransportSuppressed: readiness.liveTransportSuppressed,
			liveTerminalSuppressed: readiness.liveTerminalSuppressed,
			stateDbUntouched: readiness.stateDbUntouched,
			noModelCall: readiness.noModelCall,
			noFilesystemMutation: readiness.noFilesystemMutation,
			finalSnapshot: handoffReport.finalSnapshot,
			decisionSummaries: readiness.decisionSummaries,
			policyLogSummaries: policy.summaries(),
			sourceHandoffSummary: readiness.sourceHandoffSummary
		});
	}

	static function compactReadinessSummary(readiness:RecoveryReplayAwareKeyboardReadiness):String {
		return DiagnosticSummary.render([
			DiagnosticSummary.enumValue("kind", Std.string(readiness.kind)),
			DiagnosticSummary.enumValue("sourceHandoffKind", Std.string(readiness.sourceHandoffKind)),
			DiagnosticSummary.intValue("decisionCount", readiness.decisionCount),
			DiagnosticSummary.intValue("admittedCount", readiness.admittedCount),
			DiagnosticSummary.boolValue("postRenderIdleListReady", readiness.postRenderIdleListReady),
			DiagnosticSummary.boolValue("keyboardInputReady", readiness.keyboardInputReady),
			DiagnosticSummary.boolValue("listNavigationReady", readiness.listNavigationReady),
			DiagnosticSummary.boolValue("recoveredSelectionStableUntilNavigation", readiness.recoveredSelectionStableUntilNavigation),
			DiagnosticSummary.boolValue("navigationApplied", readiness.navigationApplied),
			DiagnosticSummary.boolValue("returnedToRecoveredSelection", readiness.returnedToRecoveredSelection),
			DiagnosticSummary.boolValue("noLeftoverScheduledRenderRequest", readiness.noLeftoverScheduledRenderRequest),
			DiagnosticSummary.intValue("sourceSchedulerRequestCount", readiness.sourceSchedulerRequestCount),
			DiagnosticSummary.intValue("consumedScheduledRequestCount", readiness.consumedScheduledRequestCount),
			DiagnosticSummary.intValue("renderCount", readiness.renderCount),
			DiagnosticSummary.boolValue("renderedSnapshotPreserved", readiness.renderedSnapshotPreserved),
			DiagnosticSummary.text("finalThread", readiness.finalThreadId),
			DiagnosticSummary.text("finalFooter", readiness.finalFooter),
			DiagnosticSummary.boolValue("finalSelectionPreserved", readiness.finalSelectionPreserved),
			DiagnosticSummary.boolValue("finalFooterPreserved", readiness.finalFooterPreserved),
			DiagnosticSummary.boolValue("inputAdmitted", readiness.inputAdmitted),
			DiagnosticSummary.boolValue("localOnlyRenderIntent", readiness.localOnlyRenderIntent),
			DiagnosticSummary.intValue("replayCount", readiness.replayCount),
			DiagnosticSummary.boolValue("snapshotOrderPreserved", readiness.snapshotOrderPreserved),
			DiagnosticSummary.boolValue("selectedMarkersPreserved", readiness.selectedMarkersPreserved),
			DiagnosticSummary.boolValue("footerSummariesPreserved", readiness.footerSummariesPreserved),
			DiagnosticSummary.boolValue("selectedMarkerMoved", readiness.selectedMarkerMoved),
			DiagnosticSummary.boolValue("recoveredSelectionRestored", readiness.recoveredSelectionRestored),
			DiagnosticSummary.intValue("sourcePreExecutionSchedulerRequestCount", readiness.sourcePreExecutionSchedulerRequestCount),
			DiagnosticSummary.intValue("sourcePreExecutionConsumedRequestCount", readiness.sourcePreExecutionConsumedRequestCount),
			DiagnosticSummary.intValue("sourcePreExecutionRenderCount", readiness.sourcePreExecutionRenderCount),
			DiagnosticSummary.boolValue("sourceRenderedSnapshotPreserved", readiness.sourceRenderedSnapshotPreserved),
			DiagnosticSummary.boolValue("stalePromptActionInactive", readiness.stalePromptActionInactive),
			DiagnosticSummary.boolValue("staleSideParentActionInactive", readiness.staleSideParentActionInactive),
			DiagnosticSummary.boolValue("staleActiveThreadActionInactive", readiness.staleActiveThreadActionInactive),
			DiagnosticSummary.boolValue("ignoredNoSurfaceAbsent", readiness.ignoredNoSurfaceRecordsAbsent),
			DiagnosticSummary.boolValue("noPressureDropRejection", readiness.noPressureDropRejection),
			DiagnosticSummary.boolValue("liveTransportSuppressed", readiness.liveTransportSuppressed),
			DiagnosticSummary.boolValue("liveTerminalSuppressed", readiness.liveTerminalSuppressed),
			DiagnosticSummary.boolValue("stateDbUntouched", readiness.stateDbUntouched),
			DiagnosticSummary.boolValue("noModelCall", readiness.noModelCall),
			DiagnosticSummary.boolValue("noFilesystemMutation", readiness.noFilesystemMutation),
			DiagnosticSummary.text("reason", readiness.reason)
		]);
	}
}
