package codexhx.runtime.tui.resume.live;

import codexhx.runtime.tui.resume.host.DeterministicResumePickerFrameScheduler;

class ResumePickerAppServerTypedResponseRecoveryPostCompletionPostRenderReplayAwareRenderedStateSixthCycleRenderRequestSchedulingRenderGate {
	public static function run():ResumePickerAppServerTypedResponseRecoveryPostCompletionPostRenderReplayAwareRenderedStateSixthCycleRenderRequestSchedulingRenderGateReport {
		final renderIntentReport = ResumePickerAppServerTypedResponseRecoveryPostCompletionPostRenderReplayAwareRenderedStateSixthCycleInputRenderIntentRenderGate.run();
		final frameScheduler = new DeterministicResumePickerFrameScheduler();
		final requestScheduler = new DeterministicResumePickerAppServerTypedResponseRecoveryPostCompletionPostRenderReplayAwareRenderedStateSixthCycleRenderRequestScheduler();
		final schedule = requestScheduler.schedule(renderIntentReport, frameScheduler);
		return new ResumePickerAppServerTypedResponseRecoveryPostCompletionPostRenderReplayAwareRenderedStateSixthCycleRenderRequestSchedulingRenderGateReport({
			scheduleKind: schedule.kind,
			scheduleSummary: schedule.summary(),
			scheduleRequested: schedule.scheduleRequested,
			scheduled: schedule.scheduled,
			scheduleSequence: schedule.scheduleSequence,
			schedulerRequestCount: frameScheduler.requestCount(),
			schedulerSummary: frameScheduler.summary(),
			localOnlyRenderIntent: schedule.localOnlyRenderIntent,
			sourceReadinessDecisionCount: renderIntentReport.sourceReadinessDecisionCount,
			sourceRenderStateCount: renderIntentReport.sourceRenderStateCount,
			sourceFrameRequests: renderIntentReport.sourceFrameRequests,
			sourceKeyboardRenderCount: renderIntentReport.sourceKeyboardRenderCount,
			replayCount: renderIntentReport.replayCount,
			sourceReplayCount: renderIntentReport.sourceReplayCount,
			sourceHandoffReplayCount: renderIntentReport.sourceHandoffReplayCount,
			sourceHandoffReadinessDecisionCount: renderIntentReport.sourceHandoffReadinessDecisionCount,
			sourceHandoffRenderStateCount: renderIntentReport.sourceHandoffRenderStateCount,
			sourceHandoffFrameRequests: renderIntentReport.sourceHandoffFrameRequests,
			sourceHandoffKeyboardRenderCount: renderIntentReport.sourceHandoffKeyboardRenderCount,
			sourceSecondCycleHandoffReplayCount: renderIntentReport.sourceSecondCycleHandoffReplayCount,
			sourceSecondCycleHandoffReadinessDecisionCount: renderIntentReport.sourceSecondCycleHandoffReadinessDecisionCount,
			sourceSecondCycleHandoffRenderStateCount: renderIntentReport.sourceSecondCycleHandoffRenderStateCount,
			sourceSecondCycleHandoffFrameRequests: renderIntentReport.sourceSecondCycleHandoffFrameRequests,
			sourceSecondCycleHandoffKeyboardRenderCount: renderIntentReport.sourceSecondCycleHandoffKeyboardRenderCount,
			sourceThirdCycleHandoffReplayCount: renderIntentReport.sourceThirdCycleHandoffReplayCount,
			sourceThirdCycleHandoffReadinessDecisionCount: renderIntentReport.sourceThirdCycleHandoffReadinessDecisionCount,
			sourceThirdCycleHandoffRenderStateCount: renderIntentReport.sourceThirdCycleHandoffRenderStateCount,
			sourceThirdCycleHandoffFrameRequests: renderIntentReport.sourceThirdCycleHandoffFrameRequests,
			sourceThirdCycleHandoffKeyboardRenderCount: renderIntentReport.sourceThirdCycleHandoffKeyboardRenderCount,
			finalThreadId: schedule.finalThreadId,
			finalFooter: schedule.finalFooter,
			finalSelectionPreserved: schedule.finalSelectionPreserved,
			finalFooterPreserved: schedule.finalFooterPreserved,
			inputAdmitted: schedule.inputAdmitted,
			completionReady: renderIntentReport.completionReady,
			nextSliceReady: renderIntentReport.nextSliceReady,
			snapshotOrderPreserved: renderIntentReport.snapshotOrderPreserved,
			selectedMarkersPreserved: renderIntentReport.selectedMarkersPreserved,
			footerSummariesPreserved: renderIntentReport.footerSummariesPreserved,
			selectedMarkerMoved: renderIntentReport.selectedMarkerMoved,
			recoveredSelectionRestored: renderIntentReport.recoveredSelectionRestored,
			noLeftoverScheduledRenderRequest: renderIntentReport.noLeftoverScheduledRenderRequest,
			sourceSchedulerRequestCount: renderIntentReport.sourceSchedulerRequestCount,
			consumedScheduledRequestCount: renderIntentReport.consumedScheduledRequestCount,
			sourcePostRenderRenderCount: renderIntentReport.sourcePostRenderRenderCount,
			renderedSnapshotPreserved: renderIntentReport.renderedSnapshotPreserved,
			sourceRenderedSnapshotPreserved: renderIntentReport.sourceRenderedSnapshotPreserved,
			sourceInputAdmitted: renderIntentReport.sourceInputAdmitted,
			sourceLocalOnlyRenderIntent: renderIntentReport.sourceLocalOnlyRenderIntent,
			sourceHandoffInputAdmitted: renderIntentReport.sourceHandoffInputAdmitted,
			sourceHandoffLocalOnlyRenderIntent: renderIntentReport.sourceHandoffLocalOnlyRenderIntent,
			sourceSecondCycleHandoffInputAdmitted: renderIntentReport.sourceSecondCycleHandoffInputAdmitted,
			sourceSecondCycleHandoffLocalOnlyRenderIntent: renderIntentReport.sourceSecondCycleHandoffLocalOnlyRenderIntent,
			sourceThirdCycleHandoffInputAdmitted: renderIntentReport.sourceThirdCycleHandoffInputAdmitted,
			sourceThirdCycleHandoffLocalOnlyRenderIntent: renderIntentReport.sourceThirdCycleHandoffLocalOnlyRenderIntent,
			sourceFourthCycleHandoffInputAdmitted: renderIntentReport.sourceFourthCycleHandoffInputAdmitted,
			sourceFourthCycleHandoffLocalOnlyRenderIntent: renderIntentReport.sourceFourthCycleHandoffLocalOnlyRenderIntent,
			stalePromptActionInactive: schedule.stalePromptActionInactive,
			staleSideParentActionInactive: schedule.staleSideParentActionInactive,
			staleActiveThreadActionInactive: schedule.staleActiveThreadActionInactive,
			ignoredNoSurfaceRecordsAbsent: schedule.ignoredNoSurfaceRecordsAbsent,
			noPressureDropRejection: schedule.noPressureDropRejection,
			liveTransportSuppressed: schedule.liveTransportSuppressed,
			liveTerminalSuppressed: schedule.liveTerminalSuppressed,
			stateDbUntouched: schedule.stateDbUntouched,
			noModelCall: schedule.noModelCall,
			noFilesystemMutation: schedule.noFilesystemMutation,
			finalSnapshot: renderIntentReport.finalSnapshot,
			renderIntentSummary: renderIntentReport.summary(),
			schedulerLogSummaries: requestScheduler.summaries()
		});
	}
}
