package codexhx.runtime.tui.resume.live;

class ThirdExecutionHandoffGate {
	public static function run():ThirdExecutionHandoffReport {
		final executionReport = ThirdScheduledRenderGate.run();
		final policy = new ThirdExecutionHandoffPolicy();
		final handoff = policy.handoff(executionReport);
		return new ThirdExecutionHandoffReport({
			handoffKind: handoff.kind,
			handoffSummary: handoff.summary(),
			postRenderIdleListReady: handoff.postRenderIdleListReady,
			keyboardInputReady: handoff.keyboardInputReady,
			listNavigationReady: handoff.listNavigationReady,
			noLeftoverScheduledRenderRequest: handoff.noLeftoverScheduledRenderRequest,
			sourceSchedulerRequestCount: handoff.sourceSchedulerRequestCount,
			consumedScheduledRequestCount: handoff.consumedScheduledRequestCount,
			renderCount: handoff.renderCount,
			renderedSnapshotPreserved: handoff.renderedSnapshotPreserved,
			finalThreadId: handoff.finalThreadId,
			finalFooter: handoff.finalFooter,
			finalSelectionPreserved: handoff.finalSelectionPreserved,
			finalFooterPreserved: handoff.finalFooterPreserved,
			inputAdmitted: handoff.inputAdmitted,
			localOnlyRenderIntent: handoff.localOnlyRenderIntent,
			completionReady: executionReport.completionReady,
			nextSliceReady: executionReport.nextSliceReady,
			replayCount: handoff.replayCount,
			sourceReplayCount: executionReport.sourceReplayCount,
			sourceHandoffReplayCount: executionReport.sourceHandoffReplayCount,
			sourceHandoffReadinessDecisionCount: executionReport.sourceHandoffReadinessDecisionCount,
			sourceHandoffRenderStateCount: executionReport.sourceHandoffRenderStateCount,
			sourceHandoffFrameRequests: executionReport.sourceHandoffFrameRequests,
			sourceHandoffKeyboardRenderCount: executionReport.sourceHandoffKeyboardRenderCount,
			sourceSecondCycleHandoffReplayCount: executionReport.sourceSecondCycleHandoffReplayCount,
			sourceSecondCycleHandoffReadinessDecisionCount: executionReport.sourceSecondCycleHandoffReadinessDecisionCount,
			sourceSecondCycleHandoffRenderStateCount: executionReport.sourceSecondCycleHandoffRenderStateCount,
			sourceSecondCycleHandoffFrameRequests: executionReport.sourceSecondCycleHandoffFrameRequests,
			sourceSecondCycleHandoffKeyboardRenderCount: executionReport.sourceSecondCycleHandoffKeyboardRenderCount,
			sourceThirdCycleHandoffReplayCount: executionReport.sourceThirdCycleHandoffReplayCount,
			sourceThirdCycleHandoffReadinessDecisionCount: executionReport.sourceThirdCycleHandoffReadinessDecisionCount,
			sourceThirdCycleHandoffRenderStateCount: executionReport.sourceThirdCycleHandoffRenderStateCount,
			sourceThirdCycleHandoffFrameRequests: executionReport.sourceThirdCycleHandoffFrameRequests,
			sourceThirdCycleHandoffKeyboardRenderCount: executionReport.sourceThirdCycleHandoffKeyboardRenderCount,
			sourceReadinessDecisionCount: executionReport.sourceReadinessDecisionCount,
			sourceRenderStateCount: executionReport.sourceRenderStateCount,
			sourceFrameRequests: executionReport.sourceFrameRequests,
			sourceKeyboardRenderCount: executionReport.sourceKeyboardRenderCount,
			snapshotOrderPreserved: handoff.snapshotOrderPreserved,
			selectedMarkersPreserved: handoff.selectedMarkersPreserved,
			footerSummariesPreserved: handoff.footerSummariesPreserved,
			selectedMarkerMoved: handoff.selectedMarkerMoved,
			recoveredSelectionRestored: handoff.recoveredSelectionRestored,
			sourcePreExecutionSchedulerRequestCount: handoff.sourcePreExecutionSchedulerRequestCount,
			sourcePreExecutionConsumedRequestCount: handoff.sourcePreExecutionConsumedRequestCount,
			sourcePreExecutionRenderCount: handoff.sourcePreExecutionRenderCount,
			sourceRenderedSnapshotPreserved: handoff.sourceRenderedSnapshotPreserved,
			sourceInputAdmitted: executionReport.sourceInputAdmitted,
			sourceLocalOnlyRenderIntent: executionReport.sourceLocalOnlyRenderIntent,
			sourceHandoffInputAdmitted: executionReport.sourceHandoffInputAdmitted,
			sourceHandoffLocalOnlyRenderIntent: executionReport.sourceHandoffLocalOnlyRenderIntent,
			sourceSecondCycleHandoffInputAdmitted: executionReport.sourceSecondCycleHandoffInputAdmitted,
			sourceSecondCycleHandoffLocalOnlyRenderIntent: executionReport.sourceSecondCycleHandoffLocalOnlyRenderIntent,
			sourceThirdCycleHandoffInputAdmitted: executionReport.sourceThirdCycleHandoffInputAdmitted,
			sourceThirdCycleHandoffLocalOnlyRenderIntent: executionReport.sourceThirdCycleHandoffLocalOnlyRenderIntent,
			stalePromptActionInactive: handoff.stalePromptActionInactive,
			staleSideParentActionInactive: handoff.staleSideParentActionInactive,
			staleActiveThreadActionInactive: handoff.staleActiveThreadActionInactive,
			ignoredNoSurfaceRecordsAbsent: handoff.ignoredNoSurfaceRecordsAbsent,
			noPressureDropRejection: handoff.noPressureDropRejection,
			liveTransportSuppressed: handoff.liveTransportSuppressed,
			liveTerminalSuppressed: handoff.liveTerminalSuppressed,
			stateDbUntouched: handoff.stateDbUntouched,
			noModelCall: handoff.noModelCall,
			noFilesystemMutation: handoff.noFilesystemMutation,
			finalSnapshot: handoff.finalSnapshot,
			executionSummary: executionReport.summary(),
			handoffLogSummaries: policy.summaries()
		});
	}
}
