package codexhx.runtime.tui.smoke;

typedef TuiSmokeTranscriptHistoryActionFields = {
	final kind:TuiSmokeTranscriptHistoryActionKind;
	final cellKind:String;
	final renderMode:String;
	final source:String;
	final message:String;
	final rawText:String;
	final transcriptText:String;
	final toolName:String;
	final status:String;
	final command:String;
	final failureCode:String;
	final width:Int;
	final displayLines:Int;
	final rawLines:Int;
	final transcriptLines:Int;
	final height:Int;
	final visibleUserTurns:Int;
	final copyEntries:Int;
	final revision:Int;
	final exitCode:Int;
	final inserted:Bool;
	final visible:Bool;
	final rawMode:Bool;
	final richMode:Bool;
	final hyperlinkAnnotated:Bool;
	final transcriptOnly:Bool;
	final activeCell:Bool;
	final activeRevisionBumped:Bool;
	final streamStarted:Bool;
	final streamConsolidated:Bool;
	final separatorInserted:Bool;
	final copyRecorded:Bool;
	final trailingBlankTrimmed:Bool;
	final remoteImagesSummarized:Bool;
	final textElementsStyled:Bool;
	final noticeHintShown:Bool;
	final warningDeduped:Bool;
	final errorInserted:Bool;
	final commandGrouped:Bool;
	final orphanHistoryInserted:Bool;
	final toolExtraImageCell:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noAppServerMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeTranscriptHistoryAction {
	public final kind:TuiSmokeTranscriptHistoryActionKind;
	public final cellKind:String;
	public final renderMode:String;
	public final source:String;
	public final message:String;
	public final rawText:String;
	public final transcriptText:String;
	public final toolName:String;
	public final status:String;
	public final command:String;
	public final failureCode:String;
	public final width:Int;
	public final displayLines:Int;
	public final rawLines:Int;
	public final transcriptLines:Int;
	public final height:Int;
	public final visibleUserTurns:Int;
	public final copyEntries:Int;
	public final revision:Int;
	public final exitCode:Int;
	public final inserted:Bool;
	public final visible:Bool;
	public final rawMode:Bool;
	public final richMode:Bool;
	public final hyperlinkAnnotated:Bool;
	public final transcriptOnly:Bool;
	public final activeCell:Bool;
	public final activeRevisionBumped:Bool;
	public final streamStarted:Bool;
	public final streamConsolidated:Bool;
	public final separatorInserted:Bool;
	public final copyRecorded:Bool;
	public final trailingBlankTrimmed:Bool;
	public final remoteImagesSummarized:Bool;
	public final textElementsStyled:Bool;
	public final noticeHintShown:Bool;
	public final warningDeduped:Bool;
	public final errorInserted:Bool;
	public final commandGrouped:Bool;
	public final orphanHistoryInserted:Bool;
	public final toolExtraImageCell:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noAppServerMutation:Bool;
	public final unsupportedRejected:Bool;
}
