package codexhx.runtime.tui.smoke;

typedef TuiSmokeTranscriptOverlayActionFields = {
	final kind:TuiSmokeTranscriptOverlayActionKind;
	final source:String;
	final title:String;
	final renderMode:String;
	final failureCode:String;
	final width:Int;
	final height:Int;
	final committedCellCount:Int;
	final liveTailLines:Int;
	final renderableCount:Int;
	final revision:Int;
	final animationTick:Int;
	final pageHeight:Int;
	final scrollOffset:Int;
	final selectedCell:Int;
	final replacedCount:Int;
	final consolidatedStart:Int;
	final consolidatedEnd:Int;
	final inserted:Bool;
	final opened:Bool;
	final closed:Bool;
	final altScreenEntered:Bool;
	final frameScheduled:Bool;
	final keyPresent:Bool;
	final recomputed:Bool;
	final cacheHit:Bool;
	final dropped:Bool;
	final followBottom:Bool;
	final streamContinuation:Bool;
	final topInset:Bool;
	final hyperlinkAnnotated:Bool;
	final rawMode:Bool;
	final richMode:Bool;
	final activeRevisionBumped:Bool;
	final animationScheduled:Bool;
	final scrolledToBottom:Bool;
	final highlightApplied:Bool;
	final highlightCleared:Bool;
	final continuousPaging:Bool;
	final roundTripped:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noAppServerMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeTranscriptOverlayAction {
	public final kind:TuiSmokeTranscriptOverlayActionKind;
	public final source:String;
	public final title:String;
	public final renderMode:String;
	public final failureCode:String;
	public final width:Int;
	public final height:Int;
	public final committedCellCount:Int;
	public final liveTailLines:Int;
	public final renderableCount:Int;
	public final revision:Int;
	public final animationTick:Int;
	public final pageHeight:Int;
	public final scrollOffset:Int;
	public final selectedCell:Int;
	public final replacedCount:Int;
	public final consolidatedStart:Int;
	public final consolidatedEnd:Int;
	public final inserted:Bool;
	public final opened:Bool;
	public final closed:Bool;
	public final altScreenEntered:Bool;
	public final frameScheduled:Bool;
	public final keyPresent:Bool;
	public final recomputed:Bool;
	public final cacheHit:Bool;
	public final dropped:Bool;
	public final followBottom:Bool;
	public final streamContinuation:Bool;
	public final topInset:Bool;
	public final hyperlinkAnnotated:Bool;
	public final rawMode:Bool;
	public final richMode:Bool;
	public final activeRevisionBumped:Bool;
	public final animationScheduled:Bool;
	public final scrolledToBottom:Bool;
	public final highlightApplied:Bool;
	public final highlightCleared:Bool;
	public final continuousPaging:Bool;
	public final roundTripped:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noAppServerMutation:Bool;
	public final unsupportedRejected:Bool;
}
