package codexhx.runtime.tui.smoke;

typedef TuiSmokeSessionFlowActionFields = {
	final kind:TuiSmokeSessionFlowActionKind;
	final display:String;
	final threadId:String;
	final previousThreadId:String;
	final threadName:String;
	final forkedFromId:String;
	final forkParentTitle:String;
	final forkNoticeTitleSource:TuiSmokeForkNoticeTitleSourceKind;
	final effectiveForkTitle:String;
	final localSessionTitle:String;
	final logId:String;
	final cwd:String;
	final workspaceRoots:String;
	final model:String;
	final reasoningEffort:String;
	final collaborationMode:String;
	final serviceTier:String;
	final personality:String;
	final approvalPolicy:String;
	final activePermissionProfile:String;
	final instructionSourceCount:Int;
	final historyEntryCount:Int;
	final queuedBefore:Int;
	final queuedAfter:Int;
	final skillsCount:Int;
	final connectorCount:Int;
	final initialMessage:String;
	final errorMessage:String;
	final failureCode:String;
	final copyHistoryReset:Bool;
	final historyMetadataSet:Bool;
	final skillsCleared:Bool;
	final networkProxySet:Bool;
	final queueSubmissionsCleared:Bool;
	final reviewDenialsReset:Bool;
	final planNudgeRefreshed:Bool;
	final turnLifecycleReset:Bool;
	final goalStatusCleared:Bool;
	final collaborationIndicatorUpdated:Bool;
	final rolloutPathSet:Bool;
	final cwdSynced:Bool;
	final workspaceRootsSynced:Bool;
	final approvalPolicySynced:Bool;
	final permissionProfileSynced:Bool;
	final permissionFallbackApplied:Bool;
	final personalitySynced:Bool;
	final projectRootCacheCleared:Bool;
	final collaborationMaskInitialized:Bool;
	final effectiveCollaborationSet:Bool;
	final modelDisplayRefreshed:Bool;
	final statusSurfacesRefreshed:Bool;
	final serviceTierCommandsSynced:Bool;
	final personalityCommandSynced:Bool;
	final pluginsCommandSynced:Bool;
	final goalCommandSynced:Bool;
	final pluginMentionsRefreshed:Bool;
	final sessionInfoInserted:Bool;
	final activeSessionHeaderCleared:Bool;
	final activeCellRevisionBumped:Bool;
	final copySourceReset:Bool;
	final skillsReloadRequested:Bool;
	final connectorsPrefetched:Bool;
	final initialMessageSubmitted:Bool;
	final initialMessageSuppressed:Bool;
	final elevatedSandboxBlocked:Bool;
	final forkNoticeInserted:Bool;
	final localSessionLookupAttempted:Bool;
	final staleLocalTitleIgnored:Bool;
	final idOnlyForkFallback:Bool;
	final requestRedraw:Bool;
	final suppressRedraw:Bool;
	final threadMatched:Bool;
	final renameConfirmationInserted:Bool;
	final queuedInputDrainAttempted:Bool;
	final noFilesystemMutation:Bool;
	final noNetwork:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeSessionFlowAction {
	public final kind:TuiSmokeSessionFlowActionKind;
	public final display:String;
	public final threadId:String;
	public final previousThreadId:String;
	public final threadName:String;
	public final forkedFromId:String;
	public final forkParentTitle:String;
	public final forkNoticeTitleSource:TuiSmokeForkNoticeTitleSourceKind;
	public final effectiveForkTitle:String;
	public final localSessionTitle:String;
	public final logId:String;
	public final cwd:String;
	public final workspaceRoots:String;
	public final model:String;
	public final reasoningEffort:String;
	public final collaborationMode:String;
	public final serviceTier:String;
	public final personality:String;
	public final approvalPolicy:String;
	public final activePermissionProfile:String;
	public final instructionSourceCount:Int;
	public final historyEntryCount:Int;
	public final queuedBefore:Int;
	public final queuedAfter:Int;
	public final skillsCount:Int;
	public final connectorCount:Int;
	public final initialMessage:String;
	public final errorMessage:String;
	public final failureCode:String;
	public final copyHistoryReset:Bool;
	public final historyMetadataSet:Bool;
	public final skillsCleared:Bool;
	public final networkProxySet:Bool;
	public final queueSubmissionsCleared:Bool;
	public final reviewDenialsReset:Bool;
	public final planNudgeRefreshed:Bool;
	public final turnLifecycleReset:Bool;
	public final goalStatusCleared:Bool;
	public final collaborationIndicatorUpdated:Bool;
	public final rolloutPathSet:Bool;
	public final cwdSynced:Bool;
	public final workspaceRootsSynced:Bool;
	public final approvalPolicySynced:Bool;
	public final permissionProfileSynced:Bool;
	public final permissionFallbackApplied:Bool;
	public final personalitySynced:Bool;
	public final projectRootCacheCleared:Bool;
	public final collaborationMaskInitialized:Bool;
	public final effectiveCollaborationSet:Bool;
	public final modelDisplayRefreshed:Bool;
	public final statusSurfacesRefreshed:Bool;
	public final serviceTierCommandsSynced:Bool;
	public final personalityCommandSynced:Bool;
	public final pluginsCommandSynced:Bool;
	public final goalCommandSynced:Bool;
	public final pluginMentionsRefreshed:Bool;
	public final sessionInfoInserted:Bool;
	public final activeSessionHeaderCleared:Bool;
	public final activeCellRevisionBumped:Bool;
	public final copySourceReset:Bool;
	public final skillsReloadRequested:Bool;
	public final connectorsPrefetched:Bool;
	public final initialMessageSubmitted:Bool;
	public final initialMessageSuppressed:Bool;
	public final elevatedSandboxBlocked:Bool;
	public final forkNoticeInserted:Bool;
	public final localSessionLookupAttempted:Bool;
	public final staleLocalTitleIgnored:Bool;
	public final idOnlyForkFallback:Bool;
	public final requestRedraw:Bool;
	public final suppressRedraw:Bool;
	public final threadMatched:Bool;
	public final renameConfirmationInserted:Bool;
	public final queuedInputDrainAttempted:Bool;
	public final noFilesystemMutation:Bool;
	public final noNetwork:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
