package codexhx.runtime.tui.smoke;

typedef TuiSmokeStatusSurfaceRenderActionFields = {
	final kind:TuiSmokeStatusSurfaceRenderActionKind;
	final source:String;
	final surface:String;
	final itemIds:String;
	final indicator:String;
	final model:String;
	final branch:String;
	final gitSummary:String;
	final rawOutputLabel:String;
	final runState:String;
	final statusHeader:String;
	final statusDetails:String;
	final warningCode:String;
	final warningMessage:String;
	final previewItems:String;
	final renderedText:String;
	final failureCode:String;
	final itemCount:Int;
	final visibleCount:Int;
	final segmentCount:Int;
	final warningCount:Int;
	final dedupeCount:Int;
	final revisionBefore:Int;
	final revisionAfter:Int;
	final statusLineEnabled:Bool;
	final terminalTitleEnabled:Bool;
	final modelVisible:Bool;
	final branchVisible:Bool;
	final gitSummaryVisible:Bool;
	final rawOutputVisible:Bool;
	final activityVisible:Bool;
	final warningsVisible:Bool;
	final warningDeduped:Bool;
	final previewStarted:Bool;
	final previewCommitted:Bool;
	final previewReverted:Bool;
	final branchRequested:Bool;
	final gitSummaryRequested:Bool;
	final hyperlinkAnnotated:Bool;
	final redrawRequested:Bool;
	final frameScheduled:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noAppServerMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeStatusSurfaceRenderAction {
	public final kind:TuiSmokeStatusSurfaceRenderActionKind;
	public final source:String;
	public final surface:String;
	public final itemIds:String;
	public final indicator:String;
	public final model:String;
	public final branch:String;
	public final gitSummary:String;
	public final rawOutputLabel:String;
	public final runState:String;
	public final statusHeader:String;
	public final statusDetails:String;
	public final warningCode:String;
	public final warningMessage:String;
	public final previewItems:String;
	public final renderedText:String;
	public final failureCode:String;
	public final itemCount:Int;
	public final visibleCount:Int;
	public final segmentCount:Int;
	public final warningCount:Int;
	public final dedupeCount:Int;
	public final revisionBefore:Int;
	public final revisionAfter:Int;
	public final statusLineEnabled:Bool;
	public final terminalTitleEnabled:Bool;
	public final modelVisible:Bool;
	public final branchVisible:Bool;
	public final gitSummaryVisible:Bool;
	public final rawOutputVisible:Bool;
	public final activityVisible:Bool;
	public final warningsVisible:Bool;
	public final warningDeduped:Bool;
	public final previewStarted:Bool;
	public final previewCommitted:Bool;
	public final previewReverted:Bool;
	public final branchRequested:Bool;
	public final gitSummaryRequested:Bool;
	public final hyperlinkAnnotated:Bool;
	public final redrawRequested:Bool;
	public final frameScheduled:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noAppServerMutation:Bool;
	public final unsupportedRejected:Bool;
}
