package codexhx.runtime.tui.smoke;

typedef TuiSmokeModelSettingsActionFields = {
	final kind:TuiSmokeModelSettingsActionKind;
	final model:String;
	final effort:String;
	final serviceTier:String;
	final personality:String;
	final audioKind:String;
	final selectedDevice:String;
	final failureCode:String;
	final itemCount:Int;
	final autoPresetCount:Int;
	final otherPresetCount:Int;
	final reasoningChoiceCount:Int;
	final featureCount:Int;
	final deviceCount:Int;
	final configuredTier:String;
	final effectiveTier:String;
	final sessionConfigured:Bool;
	final catalogReady:Bool;
	final customBaseUrlWarning:Bool;
	final currentSelected:Bool;
	final defaultSelected:Bool;
	final allModelsRow:Bool;
	final openAllModelsEvent:Bool;
	final openReasoningEvent:Bool;
	final singleEffortAutoApplied:Bool;
	final warningShown:Bool;
	final planMode:Bool;
	final planOnlySelected:Bool;
	final allModesSelected:Bool;
	final updateModel:Bool;
	final updateReasoning:Bool;
	final updatePlanReasoning:Bool;
	final persistModel:Bool;
	final persistPlanReasoning:Bool;
	final notifyPlanPrompt:Bool;
	final fastFeatureEnabled:Bool;
	final fastToggleAllowed:Bool;
	final overrideTurnContext:Bool;
	final persistServiceTier:Bool;
	final refreshSurfaces:Bool;
	final supportsPersonality:Bool;
	final persistPersonality:Bool;
	final popupOpened:Bool;
	final errorInserted:Bool;
	final defaultDeviceRow:Bool;
	final unavailableDeviceRow:Bool;
	final persistAudioDevice:Bool;
	final restartPrompt:Bool;
	final restartEvent:Bool;
	final stableFeatureOmitted:Bool;
	final configSaveOnExit:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noConfigMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeModelSettingsAction {
	public final kind:TuiSmokeModelSettingsActionKind;
	public final model:String;
	public final effort:String;
	public final serviceTier:String;
	public final personality:String;
	public final audioKind:String;
	public final selectedDevice:String;
	public final failureCode:String;
	public final itemCount:Int;
	public final autoPresetCount:Int;
	public final otherPresetCount:Int;
	public final reasoningChoiceCount:Int;
	public final featureCount:Int;
	public final deviceCount:Int;
	public final configuredTier:String;
	public final effectiveTier:String;
	public final sessionConfigured:Bool;
	public final catalogReady:Bool;
	public final customBaseUrlWarning:Bool;
	public final currentSelected:Bool;
	public final defaultSelected:Bool;
	public final allModelsRow:Bool;
	public final openAllModelsEvent:Bool;
	public final openReasoningEvent:Bool;
	public final singleEffortAutoApplied:Bool;
	public final warningShown:Bool;
	public final planMode:Bool;
	public final planOnlySelected:Bool;
	public final allModesSelected:Bool;
	public final updateModel:Bool;
	public final updateReasoning:Bool;
	public final updatePlanReasoning:Bool;
	public final persistModel:Bool;
	public final persistPlanReasoning:Bool;
	public final notifyPlanPrompt:Bool;
	public final fastFeatureEnabled:Bool;
	public final fastToggleAllowed:Bool;
	public final overrideTurnContext:Bool;
	public final persistServiceTier:Bool;
	public final refreshSurfaces:Bool;
	public final supportsPersonality:Bool;
	public final persistPersonality:Bool;
	public final popupOpened:Bool;
	public final errorInserted:Bool;
	public final defaultDeviceRow:Bool;
	public final unavailableDeviceRow:Bool;
	public final persistAudioDevice:Bool;
	public final restartPrompt:Bool;
	public final restartEvent:Bool;
	public final stableFeatureOmitted:Bool;
	public final configSaveOnExit:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noConfigMutation:Bool;
	public final unsupportedRejected:Bool;
}
