package codexhx.runtime.tui.smoke;

typedef TuiSmokeCommandLifecycleActionFields = {
	final kind:TuiSmokeCommandLifecycleActionKind;
	final callId:String;
	final processId:String;
	final source:String;
	final command:String;
	final commandDisplay:String;
	final parsedKind:String;
	final activeCell:String;
	final endTarget:String;
	final stdout:String;
	final stderr:String;
	final aggregatedOutput:String;
	final recentChunks:String;
	final footerProcesses:String;
	final statusHeader:String;
	final statusDetails:String;
	final stdin:String;
	final failureCode:String;
	final recentChunkCountBefore:Int;
	final recentChunkCountAfter:Int;
	final processCountBefore:Int;
	final processCountAfter:Int;
	final runningCommandCountBefore:Int;
	final runningCommandCountAfter:Int;
	final exitCode:Int;
	final durationMs:Int;
	final taskRunning:Bool;
	final unifiedSource:Bool;
	final startupSource:Bool;
	final standardToolCall:Bool;
	final statusEnsured:Bool;
	final answerStreamFlushed:Bool;
	final footerSynced:Bool;
	final outputTracked:Bool;
	final recentChunksTrimmed:Bool;
	final waitStreakCreated:Bool;
	final waitStreakUpdated:Bool;
	final waitStreakFlushed:Bool;
	final waitDuplicateSuppressed:Bool;
	final commandGrouped:Bool;
	final activeCellFlushed:Bool;
	final historyInserted:Bool;
	final activeCellRedrawn:Bool;
	final suppressedAfterTaskComplete:Bool;
	final suppressedExecCall:Bool;
	final queuedInputDrainRequested:Bool;
	final hadWorkActivity:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noProcessSpawn:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeCommandLifecycleAction {
	public final kind:TuiSmokeCommandLifecycleActionKind;
	public final callId:String;
	public final processId:String;
	public final source:String;
	public final command:String;
	public final commandDisplay:String;
	public final parsedKind:String;
	public final activeCell:String;
	public final endTarget:String;
	public final stdout:String;
	public final stderr:String;
	public final aggregatedOutput:String;
	public final recentChunks:String;
	public final footerProcesses:String;
	public final statusHeader:String;
	public final statusDetails:String;
	public final stdin:String;
	public final failureCode:String;
	public final recentChunkCountBefore:Int;
	public final recentChunkCountAfter:Int;
	public final processCountBefore:Int;
	public final processCountAfter:Int;
	public final runningCommandCountBefore:Int;
	public final runningCommandCountAfter:Int;
	public final exitCode:Int;
	public final durationMs:Int;
	public final taskRunning:Bool;
	public final unifiedSource:Bool;
	public final startupSource:Bool;
	public final standardToolCall:Bool;
	public final statusEnsured:Bool;
	public final answerStreamFlushed:Bool;
	public final footerSynced:Bool;
	public final outputTracked:Bool;
	public final recentChunksTrimmed:Bool;
	public final waitStreakCreated:Bool;
	public final waitStreakUpdated:Bool;
	public final waitStreakFlushed:Bool;
	public final waitDuplicateSuppressed:Bool;
	public final commandGrouped:Bool;
	public final activeCellFlushed:Bool;
	public final historyInserted:Bool;
	public final activeCellRedrawn:Bool;
	public final suppressedAfterTaskComplete:Bool;
	public final suppressedExecCall:Bool;
	public final queuedInputDrainRequested:Bool;
	public final hadWorkActivity:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noProcessSpawn:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
