package codexhx.runtime.tui.smoke;

typedef TuiSmokeClearArchiveActionFields = {
	final kind:TuiSmokeClearArchiveActionKind;
	final mode:String;
	final threadId:String;
	final sessionStartSource:String;
	final userMessageText:String;
	final failureCode:String;
	final errorMessage:String;
	final clearBackend:String;
	final exitMode:String;
	final exitReason:String;
	final transcriptCellsBefore:Int;
	final transcriptCellsAfter:Int;
	final deferredHistoryBefore:Int;
	final deferredHistoryAfter:Int;
	final pendingHistoryBefore:Int;
	final pendingHistoryAfter:Int;
	final skillWarningsBefore:Int;
	final skillWarningsAfter:Int;
	final activeSkillWarningsBefore:Int;
	final activeSkillWarningsAfter:Int;
	final activeThreadBefore:Bool;
	final activeThreadAfter:Bool;
	final sessionPreserved:Bool;
	final composerPreserved:Bool;
	final overlayCleared:Bool;
	final backtrackCleared:Bool;
	final reflowCleared:Bool;
	final replayBufferCleared:Bool;
	final headerQueued:Bool;
	final frameScheduled:Bool;
	final freshSessionStarted:Bool;
	final initialUserMessageSubmitted:Bool;
	final archiveRequested:Bool;
	final archiveSucceeded:Bool;
	final sideConversationActive:Bool;
	final errorInserted:Bool;
	final pendingShutdownThreadBefore:Bool;
	final pendingShutdownThreadAfter:Bool;
	final shutdownFeedbackShown:Bool;
	final inputDisabled:Bool;
	final appServerShutdownRequested:Bool;
	final exitRequested:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

class TuiSmokeClearArchiveAction {
	public final kind:TuiSmokeClearArchiveActionKind;
	public final mode:String;
	public final threadId:String;
	public final sessionStartSource:String;
	public final userMessageText:String;
	public final failureCode:String;
	public final errorMessage:String;
	public final clearBackend:String;
	public final exitMode:String;
	public final exitReason:String;
	public final transcriptCellsBefore:Int;
	public final transcriptCellsAfter:Int;
	public final deferredHistoryBefore:Int;
	public final deferredHistoryAfter:Int;
	public final pendingHistoryBefore:Int;
	public final pendingHistoryAfter:Int;
	public final skillWarningsBefore:Int;
	public final skillWarningsAfter:Int;
	public final activeSkillWarningsBefore:Int;
	public final activeSkillWarningsAfter:Int;
	public final activeThreadBefore:Bool;
	public final activeThreadAfter:Bool;
	public final sessionPreserved:Bool;
	public final composerPreserved:Bool;
	public final overlayCleared:Bool;
	public final backtrackCleared:Bool;
	public final reflowCleared:Bool;
	public final replayBufferCleared:Bool;
	public final headerQueued:Bool;
	public final frameScheduled:Bool;
	public final freshSessionStarted:Bool;
	public final initialUserMessageSubmitted:Bool;
	public final archiveRequested:Bool;
	public final archiveSucceeded:Bool;
	public final sideConversationActive:Bool;
	public final errorInserted:Bool;
	public final pendingShutdownThreadBefore:Bool;
	public final pendingShutdownThreadAfter:Bool;
	public final shutdownFeedbackShown:Bool;
	public final inputDisabled:Bool;
	public final appServerShutdownRequested:Bool;
	public final exitRequested:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;

	public function new(fields:TuiSmokeClearArchiveActionFields) {
		this.kind = fields.kind == null ? TuiSmokeClearArchiveActionKind.Unknown : fields.kind;
		this.mode = fields.mode == null ? "" : fields.mode;
		this.threadId = fields.threadId == null ? "" : fields.threadId;
		this.sessionStartSource = fields.sessionStartSource == null ? "" : fields.sessionStartSource;
		this.userMessageText = fields.userMessageText == null ? "" : fields.userMessageText;
		this.failureCode = fields.failureCode == null ? "" : fields.failureCode;
		this.errorMessage = fields.errorMessage == null ? "" : fields.errorMessage;
		this.clearBackend = fields.clearBackend == null ? "" : fields.clearBackend;
		this.exitMode = fields.exitMode == null ? "" : fields.exitMode;
		this.exitReason = fields.exitReason == null ? "" : fields.exitReason;
		this.transcriptCellsBefore = fields.transcriptCellsBefore;
		this.transcriptCellsAfter = fields.transcriptCellsAfter;
		this.deferredHistoryBefore = fields.deferredHistoryBefore;
		this.deferredHistoryAfter = fields.deferredHistoryAfter;
		this.pendingHistoryBefore = fields.pendingHistoryBefore;
		this.pendingHistoryAfter = fields.pendingHistoryAfter;
		this.skillWarningsBefore = fields.skillWarningsBefore;
		this.skillWarningsAfter = fields.skillWarningsAfter;
		this.activeSkillWarningsBefore = fields.activeSkillWarningsBefore;
		this.activeSkillWarningsAfter = fields.activeSkillWarningsAfter;
		this.activeThreadBefore = fields.activeThreadBefore;
		this.activeThreadAfter = fields.activeThreadAfter;
		this.sessionPreserved = fields.sessionPreserved;
		this.composerPreserved = fields.composerPreserved;
		this.overlayCleared = fields.overlayCleared;
		this.backtrackCleared = fields.backtrackCleared;
		this.reflowCleared = fields.reflowCleared;
		this.replayBufferCleared = fields.replayBufferCleared;
		this.headerQueued = fields.headerQueued;
		this.frameScheduled = fields.frameScheduled;
		this.freshSessionStarted = fields.freshSessionStarted;
		this.initialUserMessageSubmitted = fields.initialUserMessageSubmitted;
		this.archiveRequested = fields.archiveRequested;
		this.archiveSucceeded = fields.archiveSucceeded;
		this.sideConversationActive = fields.sideConversationActive;
		this.errorInserted = fields.errorInserted;
		this.pendingShutdownThreadBefore = fields.pendingShutdownThreadBefore;
		this.pendingShutdownThreadAfter = fields.pendingShutdownThreadAfter;
		this.shutdownFeedbackShown = fields.shutdownFeedbackShown;
		this.inputDisabled = fields.inputDisabled;
		this.appServerShutdownRequested = fields.appServerShutdownRequested;
		this.exitRequested = fields.exitRequested;
		this.requestRedraw = fields.requestRedraw;
		this.noLiveTerminal = fields.noLiveTerminal;
		this.noRatatuiRender = fields.noRatatuiRender;
		this.noModelCall = fields.noModelCall;
		this.unsupportedRejected = fields.unsupportedRejected;
	}
}
