package codexhx.runtime.tui.smoke;

typedef TuiSmokeReplayProtocolActionFields = {
	final kind:TuiSmokeReplayProtocolActionKind;
	final replayKind:String;
	final turnStatus:String;
	final itemType:String;
	final notificationType:String;
	final errorMessage:String;
	final failureCode:String;
	final turnId:String;
	final itemCount:Int;
	final reasoningDeltaCount:Int;
	final durationMs:Int;
	final fromReplay:Bool;
	final resumeInitialReplay:Bool;
	final threadSnapshotReplay:Bool;
	final taskStarted:Bool;
	final completionSynthesized:Bool;
	final taskCompleted:Bool;
	final interrupted:Bool;
	final failed:Bool;
	final finalizedTurn:Bool;
	final budgetLimited:Bool;
	final lastTurnIdSet:Bool;
	final lastRenderedUserCleared:Bool;
	final lastNonRetryErrorCleared:Bool;
	final lastNonRetryErrorSet:Bool;
	final retryHeaderRestored:Bool;
	final retryable:Bool;
	final streamErrorShown:Bool;
	final nonRetryHandled:Bool;
	final liveEffectsSuppressed:Bool;
	final misroutedRejected:Bool;
	final userCommitted:Bool;
	final composerHistorySeeded:Bool;
	final agentCommitted:Bool;
	final planCompleted:Bool;
	final reasoningFinalized:Bool;
	final rawReasoningShown:Bool;
	final commandStarted:Bool;
	final commandCompleted:Bool;
	final fileChangeIgnored:Bool;
	final fileChangeCompleted:Bool;
	final mcpStarted:Bool;
	final mcpCompleted:Bool;
	final webSearchCompleted:Bool;
	final imageViewOpened:Bool;
	final imageGenerationCompleted:Bool;
	final reviewEntered:Bool;
	final reviewExited:Bool;
	final contextCompacted:Bool;
	final collabToolRouted:Bool;
	final subAgentActivityRouted:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noAppServerMutation:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeReplayProtocolAction {
	public final kind:TuiSmokeReplayProtocolActionKind;
	public final replayKind:String;
	public final turnStatus:String;
	public final itemType:String;
	public final notificationType:String;
	public final errorMessage:String;
	public final failureCode:String;
	public final turnId:String;
	public final itemCount:Int;
	public final reasoningDeltaCount:Int;
	public final durationMs:Int;
	public final fromReplay:Bool;
	public final resumeInitialReplay:Bool;
	public final threadSnapshotReplay:Bool;
	public final taskStarted:Bool;
	public final completionSynthesized:Bool;
	public final taskCompleted:Bool;
	public final interrupted:Bool;
	public final failed:Bool;
	public final finalizedTurn:Bool;
	public final budgetLimited:Bool;
	public final lastTurnIdSet:Bool;
	public final lastRenderedUserCleared:Bool;
	public final lastNonRetryErrorCleared:Bool;
	public final lastNonRetryErrorSet:Bool;
	public final retryHeaderRestored:Bool;
	public final retryable:Bool;
	public final streamErrorShown:Bool;
	public final nonRetryHandled:Bool;
	public final liveEffectsSuppressed:Bool;
	public final misroutedRejected:Bool;
	public final userCommitted:Bool;
	public final composerHistorySeeded:Bool;
	public final agentCommitted:Bool;
	public final planCompleted:Bool;
	public final reasoningFinalized:Bool;
	public final rawReasoningShown:Bool;
	public final commandStarted:Bool;
	public final commandCompleted:Bool;
	public final fileChangeIgnored:Bool;
	public final fileChangeCompleted:Bool;
	public final mcpStarted:Bool;
	public final mcpCompleted:Bool;
	public final webSearchCompleted:Bool;
	public final imageViewOpened:Bool;
	public final imageGenerationCompleted:Bool;
	public final reviewEntered:Bool;
	public final reviewExited:Bool;
	public final contextCompacted:Bool;
	public final collabToolRouted:Bool;
	public final subAgentActivityRouted:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noAppServerMutation:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
