package codexhx.runtime.tui.smoke;

typedef TuiSmokeMcpStartupActionFields = {
	final kind:TuiSmokeMcpStartupActionKind;
	final server:String;
	final status:String;
	final expectedServers:String;
	final activeServers:String;
	final pendingServers:String;
	final startingServers:String;
	final failedServers:String;
	final cancelledServers:String;
	final header:String;
	final warningText:String;
	final summaryText:String;
	final failureCode:String;
	final expectedCount:Int;
	final activeCountBefore:Int;
	final activeCountAfter:Int;
	final pendingCountBefore:Int;
	final pendingCountAfter:Int;
	final completedCount:Int;
	final totalCount:Int;
	final completeWhenSettled:Bool;
	final ignoreUntilNextStartBefore:Bool;
	final ignoreUntilNextStartAfter:Bool;
	final allowTerminalOnlyBefore:Bool;
	final allowTerminalOnlyAfter:Bool;
	final sawStartingBefore:Bool;
	final sawStartingAfter:Bool;
	final pendingRoundActivated:Bool;
	final duplicateWarningSuppressed:Bool;
	final warningInserted:Bool;
	final summaryInserted:Bool;
	final statusHeaderOwned:Bool;
	final statusRestored:Bool;
	final queuedInputDrainRequested:Bool;
	final queuedInputSubmitted:Bool;
	final taskRunningBefore:Bool;
	final taskRunningAfter:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeMcpStartupAction {
	public final kind:TuiSmokeMcpStartupActionKind;
	public final server:String;
	public final status:String;
	public final expectedServers:String;
	public final activeServers:String;
	public final pendingServers:String;
	public final startingServers:String;
	public final failedServers:String;
	public final cancelledServers:String;
	public final header:String;
	public final warningText:String;
	public final summaryText:String;
	public final failureCode:String;
	public final expectedCount:Int;
	public final activeCountBefore:Int;
	public final activeCountAfter:Int;
	public final pendingCountBefore:Int;
	public final pendingCountAfter:Int;
	public final completedCount:Int;
	public final totalCount:Int;
	public final completeWhenSettled:Bool;
	public final ignoreUntilNextStartBefore:Bool;
	public final ignoreUntilNextStartAfter:Bool;
	public final allowTerminalOnlyBefore:Bool;
	public final allowTerminalOnlyAfter:Bool;
	public final sawStartingBefore:Bool;
	public final sawStartingAfter:Bool;
	public final pendingRoundActivated:Bool;
	public final duplicateWarningSuppressed:Bool;
	public final warningInserted:Bool;
	public final summaryInserted:Bool;
	public final statusHeaderOwned:Bool;
	public final statusRestored:Bool;
	public final queuedInputDrainRequested:Bool;
	public final queuedInputSubmitted:Bool;
	public final taskRunningBefore:Bool;
	public final taskRunningAfter:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
