package codexhx.runtime.tui.smoke;

typedef TuiSmokeChatWidgetInterruptedRestoreActionFields = {
	final kind:TuiSmokeChatWidgetInterruptedRestoreActionKind;
	final reason:String;
	final noticeMode:String;
	final noticeText:String;
	final failureCode:String;
	final initialMessage:String;
	final promptText:String;
	final restoredText:String;
	final composerText:String;
	final queueSource:String;
	final popOrder:String;
	final historyRecord:String;
	final currentCollaborationMode:String;
	final activeCollaborationMode:String;
	final localImageLabelsBefore:String;
	final localImageLabelsAfter:String;
	final textElementRanges:String;
	final queuedMessagesBefore:Int;
	final queuedMessagesAfter:Int;
	final pendingSteersBefore:Int;
	final pendingSteersAfter:Int;
	final pendingSteerHistoryRecords:Int;
	final pendingSteerCompareKeys:Int;
	final rejectedSteersBefore:Int;
	final rejectedSteersAfter:Int;
	final rejectedSteerHistoryRecords:Int;
	final queuedUserMessageHistoryRecords:Int;
	final remoteImageCount:Int;
	final localImageCount:Int;
	final mentionBindingCount:Int;
	final textElementCount:Int;
	final pendingPasteCount:Int;
	final cancelEditEligibleBefore:Bool;
	final cancelEditEligibleAfter:Bool;
	final cancelEditArmedBefore:Bool;
	final cancelEditArmedAfter:Bool;
	final cancelEditPromptBefore:Bool;
	final cancelEditPromptAfter:Bool;
	final composerEmpty:Bool;
	final sideConversationActive:Bool;
	final sendPendingSteersImmediately:Bool;
	final submitPendingSteersAfterInterruptBefore:Bool;
	final submitPendingSteersAfterInterruptAfter:Bool;
	final agentTurnRunningBefore:Bool;
	final agentTurnRunningAfter:Bool;
	final taskRunningBefore:Bool;
	final taskRunningAfter:Bool;
	final sleepInhibitorRunningBefore:Bool;
	final sleepInhibitorRunningAfter:Bool;
	final userTurnPendingBefore:Bool;
	final userTurnPendingAfter:Bool;
	final finalizedTurn:Bool;
	final noticeInserted:Bool;
	final noticeSuppressed:Bool;
	final pendingMerged:Bool;
	final queuedMerged:Bool;
	final composerMerged:Bool;
	final composerRestored:Bool;
	final historyFallback:Bool;
	final historyOverrideApplied:Bool;
	final inputStatePresent:Bool;
	final inputStateCleared:Bool;
	final collaborationModeRestored:Bool;
	final modelSurfacesRefreshed:Bool;
	final statusSurfacesRefreshed:Bool;
	final remoteImagesCleared:Bool;
	final pendingPastesCleared:Bool;
	final localPlaceholdersRemapped:Bool;
	final textElementsRebased:Bool;
	final cursorAtEnd:Bool;
	final cancelledTurnRestoreEventSent:Bool;
	final cancelEditPromptTaken:Bool;
	final initialMessageSubmitted:Bool;
	final initialMessageSuppressed:Bool;
	final elevatedSandboxBlocked:Bool;
	final enqueueRejectedSteerSucceeded:Bool;
	final queueAutosendSuppressed:Bool;
	final pendingPreviewRefreshed:Bool;
	final threadRollbackSent:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeChatWidgetInterruptedRestoreAction {
	public final kind:TuiSmokeChatWidgetInterruptedRestoreActionKind;
	public final reason:String;
	public final noticeMode:String;
	public final noticeText:String;
	public final failureCode:String;
	public final initialMessage:String;
	public final promptText:String;
	public final restoredText:String;
	public final composerText:String;
	public final queueSource:String;
	public final popOrder:String;
	public final historyRecord:String;
	public final currentCollaborationMode:String;
	public final activeCollaborationMode:String;
	public final localImageLabelsBefore:String;
	public final localImageLabelsAfter:String;
	public final textElementRanges:String;
	public final queuedMessagesBefore:Int;
	public final queuedMessagesAfter:Int;
	public final pendingSteersBefore:Int;
	public final pendingSteersAfter:Int;
	public final pendingSteerHistoryRecords:Int;
	public final pendingSteerCompareKeys:Int;
	public final rejectedSteersBefore:Int;
	public final rejectedSteersAfter:Int;
	public final rejectedSteerHistoryRecords:Int;
	public final queuedUserMessageHistoryRecords:Int;
	public final remoteImageCount:Int;
	public final localImageCount:Int;
	public final mentionBindingCount:Int;
	public final textElementCount:Int;
	public final pendingPasteCount:Int;
	public final cancelEditEligibleBefore:Bool;
	public final cancelEditEligibleAfter:Bool;
	public final cancelEditArmedBefore:Bool;
	public final cancelEditArmedAfter:Bool;
	public final cancelEditPromptBefore:Bool;
	public final cancelEditPromptAfter:Bool;
	public final composerEmpty:Bool;
	public final sideConversationActive:Bool;
	public final sendPendingSteersImmediately:Bool;
	public final submitPendingSteersAfterInterruptBefore:Bool;
	public final submitPendingSteersAfterInterruptAfter:Bool;
	public final agentTurnRunningBefore:Bool;
	public final agentTurnRunningAfter:Bool;
	public final taskRunningBefore:Bool;
	public final taskRunningAfter:Bool;
	public final sleepInhibitorRunningBefore:Bool;
	public final sleepInhibitorRunningAfter:Bool;
	public final userTurnPendingBefore:Bool;
	public final userTurnPendingAfter:Bool;
	public final finalizedTurn:Bool;
	public final noticeInserted:Bool;
	public final noticeSuppressed:Bool;
	public final pendingMerged:Bool;
	public final queuedMerged:Bool;
	public final composerMerged:Bool;
	public final composerRestored:Bool;
	public final historyFallback:Bool;
	public final historyOverrideApplied:Bool;
	public final inputStatePresent:Bool;
	public final inputStateCleared:Bool;
	public final collaborationModeRestored:Bool;
	public final modelSurfacesRefreshed:Bool;
	public final statusSurfacesRefreshed:Bool;
	public final remoteImagesCleared:Bool;
	public final pendingPastesCleared:Bool;
	public final localPlaceholdersRemapped:Bool;
	public final textElementsRebased:Bool;
	public final cursorAtEnd:Bool;
	public final cancelledTurnRestoreEventSent:Bool;
	public final cancelEditPromptTaken:Bool;
	public final initialMessageSubmitted:Bool;
	public final initialMessageSuppressed:Bool;
	public final elevatedSandboxBlocked:Bool;
	public final enqueueRejectedSteerSucceeded:Bool;
	public final queueAutosendSuppressed:Bool;
	public final pendingPreviewRefreshed:Bool;
	public final threadRollbackSent:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;

}
