package codexhx.runtime.tui.smoke;

typedef TuiSmokeBacktrackOverlayActionFields = {
	final kind:TuiSmokeBacktrackOverlayActionKind;
	final source:String;
	final threadId:String;
	final baseThreadId:String;
	final message:String;
	final prefill:String;
	final failureCode:String;
	final direction:String;
	final userCount:Int;
	final nthUserMessage:Int;
	final cellIndex:Int;
	final previousNthUserMessage:Int;
	final nextNthUserMessage:Int;
	final numTurns:Int;
	final originalCellCount:Int;
	final trimmedCellCount:Int;
	final copyHistoryUserCount:Int;
	final remoteImageCount:Int;
	final localImageCount:Int;
	final textElementCount:Int;
	final composerEmpty:Bool;
	final primed:Bool;
	final baseThreadCaptured:Bool;
	final hintShown:Bool;
	final targetAvailable:Bool;
	final overlayOpened:Bool;
	final overlayPreviewActive:Bool;
	final altScreenEntered:Bool;
	final frameScheduled:Bool;
	final hintCleared:Bool;
	final highlightApplied:Bool;
	final highlightCleared:Bool;
	final steppedOlder:Bool;
	final steppedNewer:Bool;
	final clamped:Bool;
	final confirmed:Bool;
	final closed:Bool;
	final selectionMatchedThread:Bool;
	final pendingRollbackSet:Bool;
	final pendingRollbackCleared:Bool;
	final pendingRollbackBlocked:Bool;
	final rollbackSubmitted:Bool;
	final composerPrefilled:Bool;
	final remoteImagesRestored:Bool;
	final copyHistoryTruncated:Bool;
	final overlayReplaced:Bool;
	final deferredHistoryCleared:Bool;
	final renderPending:Bool;
	final ignoredThreadMismatch:Bool;
	final stateReset:Bool;
	final infoInserted:Bool;
	final sideConversationRejected:Bool;
	final vimInsertAllowed:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noAppServerMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeBacktrackOverlayAction {
	public final kind:TuiSmokeBacktrackOverlayActionKind;
	public final source:String;
	public final threadId:String;
	public final baseThreadId:String;
	public final message:String;
	public final prefill:String;
	public final failureCode:String;
	public final direction:String;
	public final userCount:Int;
	public final nthUserMessage:Int;
	public final cellIndex:Int;
	public final previousNthUserMessage:Int;
	public final nextNthUserMessage:Int;
	public final numTurns:Int;
	public final originalCellCount:Int;
	public final trimmedCellCount:Int;
	public final copyHistoryUserCount:Int;
	public final remoteImageCount:Int;
	public final localImageCount:Int;
	public final textElementCount:Int;
	public final composerEmpty:Bool;
	public final primed:Bool;
	public final baseThreadCaptured:Bool;
	public final hintShown:Bool;
	public final targetAvailable:Bool;
	public final overlayOpened:Bool;
	public final overlayPreviewActive:Bool;
	public final altScreenEntered:Bool;
	public final frameScheduled:Bool;
	public final hintCleared:Bool;
	public final highlightApplied:Bool;
	public final highlightCleared:Bool;
	public final steppedOlder:Bool;
	public final steppedNewer:Bool;
	public final clamped:Bool;
	public final confirmed:Bool;
	public final closed:Bool;
	public final selectionMatchedThread:Bool;
	public final pendingRollbackSet:Bool;
	public final pendingRollbackCleared:Bool;
	public final pendingRollbackBlocked:Bool;
	public final rollbackSubmitted:Bool;
	public final composerPrefilled:Bool;
	public final remoteImagesRestored:Bool;
	public final copyHistoryTruncated:Bool;
	public final overlayReplaced:Bool;
	public final deferredHistoryCleared:Bool;
	public final renderPending:Bool;
	public final ignoredThreadMismatch:Bool;
	public final stateReset:Bool;
	public final infoInserted:Bool;
	public final sideConversationRejected:Bool;
	public final vimInsertAllowed:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noAppServerMutation:Bool;
	public final unsupportedRejected:Bool;
}
