package codexhx.runtime.tui.smoke;

typedef TuiSmokeSideConversationActionFields = {
	final kind:TuiSmokeSideConversationActionKind;
	final handoffMode:TuiSmokeAppThreadInputHandoffMode;
	final replayRoute:TuiSmokeThreadSnapshotReplayRoute;
	final activeEventKind:TuiSmokeActiveThreadEventKind;
	final shutdownRoute:TuiSmokeActiveThreadShutdownRoute;
	final skillsListRoute:TuiSmokeSkillsListResponseRoute;
	final parentThreadId:String;
	final childThreadId:String;
	final targetThreadId:String;
	final activeThreadId:String;
	final sourceThreadId:String;
	final primaryThreadId:String;
	final closedThreadId:String;
	final pendingShutdownThreadId:String;
	final cwd:String;
	final status:String;
	final statusChange:String;
	final label:String;
	final blockMessage:String;
	final failureCode:String;
	final userMessageText:String;
	final errorMessage:String;
	final eventId:String;
	final sideThreadsBefore:Int;
	final sideThreadsAfter:Int;
	final pendingInputCount:Int;
	final replayTurnCount:Int;
	final replayEventCount:Int;
	final replayNoticeCount:Int;
	final replaySuppressedNoticeCount:Int;
	final skillCount:Int;
	final cwdSkillErrorCount:Int;
	final newlyActiveWarningCount:Int;
	final cachedWarningCount:Int;
	final emittedWarningEventCount:Int;
	final remoteImageCount:Int;
	final localImageCount:Int;
	final mentionBindingCount:Int;
	final parentIsMain:Bool;
	final sideConversationActiveBefore:Bool;
	final sideConversationActiveAfter:Bool;
	final noticeSuppressedBefore:Bool;
	final noticeSuppressedAfter:Bool;
	final renameBlockedBefore:Bool;
	final renameBlockedAfter:Bool;
	final overlayActive:Bool;
	final modalOrPopupActive:Bool;
	final composerEmpty:Bool;
	final parentStatusActionable:Bool;
	final forkConfigEphemeral:Bool;
	final approvalPolicyInherited:Bool;
	final sandboxPolicyInherited:Bool;
	final developerInstructionsAdded:Bool;
	final mainThreadGuardrail:Bool;
	final inheritedHistoryReferenceOnly:Bool;
	final boundaryInstructionsOnly:Bool;
	final noInheritedTaskContinuation:Bool;
	final toolHistoryReferenceOnly:Bool;
	final nonMutatingInspectionAllowed:Bool;
	final mutationRequiresSideRequest:Bool;
	final escalatedPermissionBlocked:Bool;
	final transcriptEmpty:Bool;
	final modelInherited:Bool;
	final serviceTierInherited:Bool;
	final boundaryInjected:Bool;
	final hiddenBoundaryPrompt:Bool;
	final switchedToChild:Bool;
	final switchedToParent:Bool;
	final submittedInitialUserMessage:Bool;
	final restoredComposer:Bool;
	final returnRequested:Bool;
	final returnedToParent:Bool;
	final interruptSubmitted:Bool;
	final startupInterruptUsed:Bool;
	final turnInterruptUsed:Bool;
	final threadUnsubscribed:Bool;
	final localStateDiscarded:Bool;
	final listenerAborted:Bool;
	final channelRemoved:Bool;
	final navigationRemoved:Bool;
	final activeThreadCleared:Bool;
	final approvalsRefreshed:Bool;
	final statusSynced:Bool;
	final activeThreadPresent:Bool;
	final activeThreadStored:Bool;
	final receiverStored:Bool;
	final inputStateCaptured:Bool;
	final snapshotStored:Bool;
	final snapshotInputStatePresent:Bool;
	final targetActivated:Bool;
	final restoredIntoTarget:Bool;
	final missingSnapshotFallback:Bool;
	final sideThreadTarget:Bool;
	final currentThreadTarget:Bool;
	final pendingInputPreserved:Bool;
	final statusSurfacesRefreshed:Bool;
	final resizeReflowEnabled:Bool;
	final snapshotHasTurns:Bool;
	final snapshotHasEvents:Bool;
	final bufferReplayStarted:Bool;
	final bufferReplayEnded:Bool;
	final pendingInteractiveRequest:Bool;
	final sessionHandled:Bool;
	final queueAutosendSuppressedBefore:Bool;
	final queueAutosendSuppressedAfter:Bool;
	final turnsReplayed:Bool;
	final eventsReplayed:Bool;
	final noticesSuppressed:Bool;
	final initialSubmitReleased:Bool;
	final pendingInitialSubmitSubmitted:Bool;
	final resumeRestoredQueue:Bool;
	final queuedInputDrained:Bool;
	final pendingRequestRegistered:Bool;
	final notificationDelivered:Bool;
	final requestDelivered:Bool;
	final requestSkipped:Bool;
	final historyEntryRouted:Bool;
	final feedbackRouted:Bool;
	final collabReceiverCached:Bool;
	final rollbackStoreApplied:Bool;
	final activeReceiverDrained:Bool;
	final activeReceiverRestored:Bool;
	final receiverDisconnected:Bool;
	final shutdownNotification:Bool;
	final nonPrimaryActive:Bool;
	final failoverEligible:Bool;
	final failoverSelectedPrimary:Bool;
	final failoverDiscardedSide:Bool;
	final failoverInfoMessage:Bool;
	final failoverErrorMessage:Bool;
	final pendingShutdownMatched:Bool;
	final pendingShutdownCleared:Bool;
	final ordinaryEventForwarded:Bool;
	final appExitRequested:Bool;
	final cwdScopedErrors:Bool;
	final newlyActiveFiltered:Bool;
	final duplicateWarningsSuppressed:Bool;
	final warningStateCleared:Bool;
	final warningAppEventEmitted:Bool;
	final responseForwardedToChatWidget:Bool;
	final skillsAppliedToChatWidget:Bool;
	final filesystemReadAvoided:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeSideConversationAction {
	@:recordDefault(TuiSmokeSideConversationActionKind.Unknown)
	public final kind:TuiSmokeSideConversationActionKind;
	@:recordDefault(TuiSmokeAppThreadInputHandoffMode.Unknown)
	public final handoffMode:TuiSmokeAppThreadInputHandoffMode;
	@:recordDefault(TuiSmokeThreadSnapshotReplayRoute.Unknown)
	public final replayRoute:TuiSmokeThreadSnapshotReplayRoute;
	@:recordDefault(TuiSmokeActiveThreadEventKind.Unknown)
	public final activeEventKind:TuiSmokeActiveThreadEventKind;
	@:recordDefault(TuiSmokeActiveThreadShutdownRoute.Unknown)
	public final shutdownRoute:TuiSmokeActiveThreadShutdownRoute;
	@:recordDefault(TuiSmokeSkillsListResponseRoute.Unknown)
	public final skillsListRoute:TuiSmokeSkillsListResponseRoute;
	public final parentThreadId:String;
	public final childThreadId:String;
	public final targetThreadId:String;
	public final activeThreadId:String;
	public final sourceThreadId:String;
	public final primaryThreadId:String;
	public final closedThreadId:String;
	public final pendingShutdownThreadId:String;
	public final cwd:String;
	public final status:String;
	public final statusChange:String;
	public final label:String;
	public final blockMessage:String;
	public final failureCode:String;
	public final userMessageText:String;
	public final errorMessage:String;
	public final eventId:String;
	public final sideThreadsBefore:Int;
	public final sideThreadsAfter:Int;
	public final pendingInputCount:Int;
	public final replayTurnCount:Int;
	public final replayEventCount:Int;
	public final replayNoticeCount:Int;
	public final replaySuppressedNoticeCount:Int;
	public final skillCount:Int;
	public final cwdSkillErrorCount:Int;
	public final newlyActiveWarningCount:Int;
	public final cachedWarningCount:Int;
	public final emittedWarningEventCount:Int;
	public final remoteImageCount:Int;
	public final localImageCount:Int;
	public final mentionBindingCount:Int;
	public final parentIsMain:Bool;
	public final sideConversationActiveBefore:Bool;
	public final sideConversationActiveAfter:Bool;
	public final noticeSuppressedBefore:Bool;
	public final noticeSuppressedAfter:Bool;
	public final renameBlockedBefore:Bool;
	public final renameBlockedAfter:Bool;
	public final overlayActive:Bool;
	public final modalOrPopupActive:Bool;
	public final composerEmpty:Bool;
	public final parentStatusActionable:Bool;
	public final forkConfigEphemeral:Bool;
	public final approvalPolicyInherited:Bool;
	public final sandboxPolicyInherited:Bool;
	public final developerInstructionsAdded:Bool;
	public final mainThreadGuardrail:Bool;
	public final inheritedHistoryReferenceOnly:Bool;
	public final boundaryInstructionsOnly:Bool;
	public final noInheritedTaskContinuation:Bool;
	public final toolHistoryReferenceOnly:Bool;
	public final nonMutatingInspectionAllowed:Bool;
	public final mutationRequiresSideRequest:Bool;
	public final escalatedPermissionBlocked:Bool;
	public final transcriptEmpty:Bool;
	public final modelInherited:Bool;
	public final serviceTierInherited:Bool;
	public final boundaryInjected:Bool;
	public final hiddenBoundaryPrompt:Bool;
	public final switchedToChild:Bool;
	public final switchedToParent:Bool;
	public final submittedInitialUserMessage:Bool;
	public final restoredComposer:Bool;
	public final returnRequested:Bool;
	public final returnedToParent:Bool;
	public final interruptSubmitted:Bool;
	public final startupInterruptUsed:Bool;
	public final turnInterruptUsed:Bool;
	public final threadUnsubscribed:Bool;
	public final localStateDiscarded:Bool;
	public final listenerAborted:Bool;
	public final channelRemoved:Bool;
	public final navigationRemoved:Bool;
	public final activeThreadCleared:Bool;
	public final approvalsRefreshed:Bool;
	public final statusSynced:Bool;
	public final activeThreadPresent:Bool;
	public final activeThreadStored:Bool;
	public final receiverStored:Bool;
	public final inputStateCaptured:Bool;
	public final snapshotStored:Bool;
	public final snapshotInputStatePresent:Bool;
	public final targetActivated:Bool;
	public final restoredIntoTarget:Bool;
	public final missingSnapshotFallback:Bool;
	public final sideThreadTarget:Bool;
	public final currentThreadTarget:Bool;
	public final pendingInputPreserved:Bool;
	public final statusSurfacesRefreshed:Bool;
	public final resizeReflowEnabled:Bool;
	public final snapshotHasTurns:Bool;
	public final snapshotHasEvents:Bool;
	public final bufferReplayStarted:Bool;
	public final bufferReplayEnded:Bool;
	public final pendingInteractiveRequest:Bool;
	public final sessionHandled:Bool;
	public final queueAutosendSuppressedBefore:Bool;
	public final queueAutosendSuppressedAfter:Bool;
	public final turnsReplayed:Bool;
	public final eventsReplayed:Bool;
	public final noticesSuppressed:Bool;
	public final initialSubmitReleased:Bool;
	public final pendingInitialSubmitSubmitted:Bool;
	public final resumeRestoredQueue:Bool;
	public final queuedInputDrained:Bool;
	public final pendingRequestRegistered:Bool;
	public final notificationDelivered:Bool;
	public final requestDelivered:Bool;
	public final requestSkipped:Bool;
	public final historyEntryRouted:Bool;
	public final feedbackRouted:Bool;
	public final collabReceiverCached:Bool;
	public final rollbackStoreApplied:Bool;
	public final activeReceiverDrained:Bool;
	public final activeReceiverRestored:Bool;
	public final receiverDisconnected:Bool;
	public final shutdownNotification:Bool;
	public final nonPrimaryActive:Bool;
	public final failoverEligible:Bool;
	public final failoverSelectedPrimary:Bool;
	public final failoverDiscardedSide:Bool;
	public final failoverInfoMessage:Bool;
	public final failoverErrorMessage:Bool;
	public final pendingShutdownMatched:Bool;
	public final pendingShutdownCleared:Bool;
	public final ordinaryEventForwarded:Bool;
	public final appExitRequested:Bool;
	public final cwdScopedErrors:Bool;
	public final newlyActiveFiltered:Bool;
	public final duplicateWarningsSuppressed:Bool;
	public final warningStateCleared:Bool;
	public final warningAppEventEmitted:Bool;
	public final responseForwardedToChatWidget:Bool;
	public final skillsAppliedToChatWidget:Bool;
	public final filesystemReadAvoided:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
