package codexhx.runtime.tui.smoke;

typedef TuiSmokeChatWidgetStreamLifecycleActionFields = {
	final kind:TuiSmokeChatWidgetStreamLifecycleActionKind;
	final interruptKind:String;
	final finishReason:String;
	final failureCode:String;
	final delta:String;
	final queuedInterruptsBefore:Int;
	final queuedInterruptsAfter:Int;
	final queuedLinesBefore:Int;
	final queuedLinesAfter:Int;
	final committedCells:Int;
	final activeStreamControllerBefore:Bool;
	final activeStreamControllerAfter:Bool;
	final planStreamControllerBefore:Bool;
	final planStreamControllerAfter:Bool;
	final activeTailBefore:Bool;
	final activeTailAfter:Bool;
	final taskCompletePendingBefore:Bool;
	final taskCompletePendingAfter:Bool;
	final taskRunningBefore:Bool;
	final taskRunningAfter:Bool;
	final statusHidden:Bool;
	final statusPreserved:Bool;
	final pendingStatusRestoreBefore:Bool;
	final pendingStatusRestoreAfter:Bool;
	final interruptQueued:Bool;
	final interruptHandled:Bool;
	final fifoPreserved:Bool;
	final flushedInterrupts:Int;
	final startCommitAnimation:Bool;
	final stopCommitAnimation:Bool;
	final catchUpTick:Bool;
	final adaptiveChunkingReset:Bool;
	final runningCommandsCleared:Bool;
	final suppressedExecCleared:Bool;
	final unifiedWaitCleared:Bool;
	final cancelEditCleared:Bool;
	final rateLimitPromptChecked:Bool;
	final taskStateUpdated:Bool;
	final statusSurfacesRefreshed:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

class TuiSmokeChatWidgetStreamLifecycleAction {
	public final kind:TuiSmokeChatWidgetStreamLifecycleActionKind;
	public final interruptKind:String;
	public final finishReason:String;
	public final failureCode:String;
	public final delta:String;
	public final queuedInterruptsBefore:Int;
	public final queuedInterruptsAfter:Int;
	public final queuedLinesBefore:Int;
	public final queuedLinesAfter:Int;
	public final committedCells:Int;
	public final activeStreamControllerBefore:Bool;
	public final activeStreamControllerAfter:Bool;
	public final planStreamControllerBefore:Bool;
	public final planStreamControllerAfter:Bool;
	public final activeTailBefore:Bool;
	public final activeTailAfter:Bool;
	public final taskCompletePendingBefore:Bool;
	public final taskCompletePendingAfter:Bool;
	public final taskRunningBefore:Bool;
	public final taskRunningAfter:Bool;
	public final statusHidden:Bool;
	public final statusPreserved:Bool;
	public final pendingStatusRestoreBefore:Bool;
	public final pendingStatusRestoreAfter:Bool;
	public final interruptQueued:Bool;
	public final interruptHandled:Bool;
	public final fifoPreserved:Bool;
	public final flushedInterrupts:Int;
	public final startCommitAnimation:Bool;
	public final stopCommitAnimation:Bool;
	public final catchUpTick:Bool;
	public final adaptiveChunkingReset:Bool;
	public final runningCommandsCleared:Bool;
	public final suppressedExecCleared:Bool;
	public final unifiedWaitCleared:Bool;
	public final cancelEditCleared:Bool;
	public final rateLimitPromptChecked:Bool;
	public final taskStateUpdated:Bool;
	public final statusSurfacesRefreshed:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;

	public function new(fields:TuiSmokeChatWidgetStreamLifecycleActionFields) {
		this.kind = fields.kind == null ? TuiSmokeChatWidgetStreamLifecycleActionKind.Unknown : fields.kind;
		this.interruptKind = fields.interruptKind == null ? "" : fields.interruptKind;
		this.finishReason = fields.finishReason == null ? "" : fields.finishReason;
		this.failureCode = fields.failureCode == null ? "" : fields.failureCode;
		this.delta = fields.delta == null ? "" : fields.delta;
		this.queuedInterruptsBefore = fields.queuedInterruptsBefore;
		this.queuedInterruptsAfter = fields.queuedInterruptsAfter;
		this.queuedLinesBefore = fields.queuedLinesBefore;
		this.queuedLinesAfter = fields.queuedLinesAfter;
		this.committedCells = fields.committedCells;
		this.activeStreamControllerBefore = fields.activeStreamControllerBefore;
		this.activeStreamControllerAfter = fields.activeStreamControllerAfter;
		this.planStreamControllerBefore = fields.planStreamControllerBefore;
		this.planStreamControllerAfter = fields.planStreamControllerAfter;
		this.activeTailBefore = fields.activeTailBefore;
		this.activeTailAfter = fields.activeTailAfter;
		this.taskCompletePendingBefore = fields.taskCompletePendingBefore;
		this.taskCompletePendingAfter = fields.taskCompletePendingAfter;
		this.taskRunningBefore = fields.taskRunningBefore;
		this.taskRunningAfter = fields.taskRunningAfter;
		this.statusHidden = fields.statusHidden;
		this.statusPreserved = fields.statusPreserved;
		this.pendingStatusRestoreBefore = fields.pendingStatusRestoreBefore;
		this.pendingStatusRestoreAfter = fields.pendingStatusRestoreAfter;
		this.interruptQueued = fields.interruptQueued;
		this.interruptHandled = fields.interruptHandled;
		this.fifoPreserved = fields.fifoPreserved;
		this.flushedInterrupts = fields.flushedInterrupts;
		this.startCommitAnimation = fields.startCommitAnimation;
		this.stopCommitAnimation = fields.stopCommitAnimation;
		this.catchUpTick = fields.catchUpTick;
		this.adaptiveChunkingReset = fields.adaptiveChunkingReset;
		this.runningCommandsCleared = fields.runningCommandsCleared;
		this.suppressedExecCleared = fields.suppressedExecCleared;
		this.unifiedWaitCleared = fields.unifiedWaitCleared;
		this.cancelEditCleared = fields.cancelEditCleared;
		this.rateLimitPromptChecked = fields.rateLimitPromptChecked;
		this.taskStateUpdated = fields.taskStateUpdated;
		this.statusSurfacesRefreshed = fields.statusSurfacesRefreshed;
		this.requestRedraw = fields.requestRedraw;
		this.noLiveTerminal = fields.noLiveTerminal;
		this.noRatatuiRender = fields.noRatatuiRender;
		this.noModelCall = fields.noModelCall;
		this.unsupportedRejected = fields.unsupportedRejected;
	}
}
