package codexhx.runtime.tui.smoke;

typedef TuiSmokeSideConversationActionFields = {
	final kind:TuiSmokeSideConversationActionKind;
	final handoffMode:TuiSmokeAppThreadInputHandoffMode;
	final parentThreadId:String;
	final childThreadId:String;
	final targetThreadId:String;
	final activeThreadId:String;
	final sourceThreadId:String;
	final status:String;
	final statusChange:String;
	final label:String;
	final blockMessage:String;
	final failureCode:String;
	final userMessageText:String;
	final errorMessage:String;
	final sideThreadsBefore:Int;
	final sideThreadsAfter:Int;
	final pendingInputCount:Int;
	final remoteImageCount:Int;
	final localImageCount:Int;
	final mentionBindingCount:Int;
	final parentIsMain:Bool;
	final sideConversationActiveBefore:Bool;
	final sideConversationActiveAfter:Bool;
	final noticeSuppressedBefore:Bool;
	final noticeSuppressedAfter:Bool;
	final renameBlockedBefore:Bool;
	final renameBlockedAfter:Bool;
	final overlayActive:Bool;
	final modalOrPopupActive:Bool;
	final composerEmpty:Bool;
	final parentStatusActionable:Bool;
	final forkConfigEphemeral:Bool;
	final developerInstructionsAdded:Bool;
	final modelInherited:Bool;
	final serviceTierInherited:Bool;
	final boundaryInjected:Bool;
	final hiddenBoundaryPrompt:Bool;
	final switchedToChild:Bool;
	final switchedToParent:Bool;
	final submittedInitialUserMessage:Bool;
	final restoredComposer:Bool;
	final returnRequested:Bool;
	final returnedToParent:Bool;
	final interruptSubmitted:Bool;
	final startupInterruptUsed:Bool;
	final turnInterruptUsed:Bool;
	final threadUnsubscribed:Bool;
	final localStateDiscarded:Bool;
	final listenerAborted:Bool;
	final channelRemoved:Bool;
	final navigationRemoved:Bool;
	final activeThreadCleared:Bool;
	final approvalsRefreshed:Bool;
	final statusSynced:Bool;
	final activeThreadPresent:Bool;
	final activeThreadStored:Bool;
	final receiverStored:Bool;
	final inputStateCaptured:Bool;
	final snapshotStored:Bool;
	final snapshotInputStatePresent:Bool;
	final targetActivated:Bool;
	final restoredIntoTarget:Bool;
	final missingSnapshotFallback:Bool;
	final sideThreadTarget:Bool;
	final currentThreadTarget:Bool;
	final pendingInputPreserved:Bool;
	final statusSurfacesRefreshed:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeSideConversationAction {
	@:recordDefault(TuiSmokeSideConversationActionKind.Unknown)
	public final kind:TuiSmokeSideConversationActionKind;
	@:recordDefault(TuiSmokeAppThreadInputHandoffMode.Unknown)
	public final handoffMode:TuiSmokeAppThreadInputHandoffMode;
	public final parentThreadId:String;
	public final childThreadId:String;
	public final targetThreadId:String;
	public final activeThreadId:String;
	public final sourceThreadId:String;
	public final status:String;
	public final statusChange:String;
	public final label:String;
	public final blockMessage:String;
	public final failureCode:String;
	public final userMessageText:String;
	public final errorMessage:String;
	public final sideThreadsBefore:Int;
	public final sideThreadsAfter:Int;
	public final pendingInputCount:Int;
	public final remoteImageCount:Int;
	public final localImageCount:Int;
	public final mentionBindingCount:Int;
	public final parentIsMain:Bool;
	public final sideConversationActiveBefore:Bool;
	public final sideConversationActiveAfter:Bool;
	public final noticeSuppressedBefore:Bool;
	public final noticeSuppressedAfter:Bool;
	public final renameBlockedBefore:Bool;
	public final renameBlockedAfter:Bool;
	public final overlayActive:Bool;
	public final modalOrPopupActive:Bool;
	public final composerEmpty:Bool;
	public final parentStatusActionable:Bool;
	public final forkConfigEphemeral:Bool;
	public final developerInstructionsAdded:Bool;
	public final modelInherited:Bool;
	public final serviceTierInherited:Bool;
	public final boundaryInjected:Bool;
	public final hiddenBoundaryPrompt:Bool;
	public final switchedToChild:Bool;
	public final switchedToParent:Bool;
	public final submittedInitialUserMessage:Bool;
	public final restoredComposer:Bool;
	public final returnRequested:Bool;
	public final returnedToParent:Bool;
	public final interruptSubmitted:Bool;
	public final startupInterruptUsed:Bool;
	public final turnInterruptUsed:Bool;
	public final threadUnsubscribed:Bool;
	public final localStateDiscarded:Bool;
	public final listenerAborted:Bool;
	public final channelRemoved:Bool;
	public final navigationRemoved:Bool;
	public final activeThreadCleared:Bool;
	public final approvalsRefreshed:Bool;
	public final statusSynced:Bool;
	public final activeThreadPresent:Bool;
	public final activeThreadStored:Bool;
	public final receiverStored:Bool;
	public final inputStateCaptured:Bool;
	public final snapshotStored:Bool;
	public final snapshotInputStatePresent:Bool;
	public final targetActivated:Bool;
	public final restoredIntoTarget:Bool;
	public final missingSnapshotFallback:Bool;
	public final sideThreadTarget:Bool;
	public final currentThreadTarget:Bool;
	public final pendingInputPreserved:Bool;
	public final statusSurfacesRefreshed:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
