package codexhx.runtime.tui.smoke;

typedef TuiSmokeChatWidgetInterruptQuitActionFields = {
	final kind:TuiSmokeChatWidgetInterruptQuitActionKind;
	final ctrlCPrecedence:TuiSmokeChatWidgetCtrlCPrecedenceKind;
	final interruptKeyRoute:TuiSmokeChatWidgetInterruptKeyRouteKind;
	final shortcutTransition:TuiSmokeChatWidgetQuitShortcutTransitionKind;
	final key:String;
	final activeShortcutKeyBefore:String;
	final activeShortcutKeyAfter:String;
	final route:String;
	final exitMode:String;
	final failureCode:String;
	final doublePressEnabled:Bool;
	final realtimeLive:Bool;
	final realtimeStopped:Bool;
	final modalOrPopupActive:Bool;
	final bottomPaneAttempted:Bool;
	final bottomPaneHandled:Bool;
	final cancellableWorkActive:Bool;
	final taskRunning:Bool;
	final reviewMode:Bool;
	final composerEmpty:Bool;
	final quitShortcutActiveBefore:Bool;
	final quitShortcutActiveAfter:Bool;
	final quitShortcutKeyMatched:Bool;
	final quitShortcutHintShown:Bool;
	final quitShortcutHintCleared:Bool;
	final quitShortcutExpired:Bool;
	final interruptSubmitted:Bool;
	final interruptRestoresPrompt:Bool;
	final interruptBindingMatched:Bool;
	final pendingSteersBefore:Int;
	final pendingSteersAfter:Int;
	final submitPendingSteersAfterInterrupt:Bool;
	final queuedSteerSubmittedAfterInterrupt:Bool;
	final reviewWarningInserted:Bool;
	final activeGoalPaused:Bool;
	final streamQueueCleared:Bool;
	final planStreamQueueCleared:Bool;
	final activeTailCleared:Bool;
	final cancelEditArmedBefore:Bool;
	final cancelEditArmedAfter:Bool;
	final cancelEditCleared:Bool;
	final appExitSent:Bool;
	final shutdownFeedbackShown:Bool;
	final appServerShutdownRequested:Bool;
	final pendingShutdownThreadBefore:Bool;
	final pendingShutdownThreadAfter:Bool;
	final inputDisabled:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeChatWidgetInterruptQuitAction {
	public final kind:TuiSmokeChatWidgetInterruptQuitActionKind;
	public final ctrlCPrecedence:TuiSmokeChatWidgetCtrlCPrecedenceKind;
	public final interruptKeyRoute:TuiSmokeChatWidgetInterruptKeyRouteKind;
	public final shortcutTransition:TuiSmokeChatWidgetQuitShortcutTransitionKind;
	public final key:String;
	public final activeShortcutKeyBefore:String;
	public final activeShortcutKeyAfter:String;
	public final route:String;
	public final exitMode:String;
	public final failureCode:String;
	public final doublePressEnabled:Bool;
	public final realtimeLive:Bool;
	public final realtimeStopped:Bool;
	public final modalOrPopupActive:Bool;
	public final bottomPaneAttempted:Bool;
	public final bottomPaneHandled:Bool;
	public final cancellableWorkActive:Bool;
	public final taskRunning:Bool;
	public final reviewMode:Bool;
	public final composerEmpty:Bool;
	public final quitShortcutActiveBefore:Bool;
	public final quitShortcutActiveAfter:Bool;
	public final quitShortcutKeyMatched:Bool;
	public final quitShortcutHintShown:Bool;
	public final quitShortcutHintCleared:Bool;
	public final quitShortcutExpired:Bool;
	public final interruptSubmitted:Bool;
	public final interruptRestoresPrompt:Bool;
	public final interruptBindingMatched:Bool;
	public final pendingSteersBefore:Int;
	public final pendingSteersAfter:Int;
	public final submitPendingSteersAfterInterrupt:Bool;
	public final queuedSteerSubmittedAfterInterrupt:Bool;
	public final reviewWarningInserted:Bool;
	public final activeGoalPaused:Bool;
	public final streamQueueCleared:Bool;
	public final planStreamQueueCleared:Bool;
	public final activeTailCleared:Bool;
	public final cancelEditArmedBefore:Bool;
	public final cancelEditArmedAfter:Bool;
	public final cancelEditCleared:Bool;
	public final appExitSent:Bool;
	public final shutdownFeedbackShown:Bool;
	public final appServerShutdownRequested:Bool;
	public final pendingShutdownThreadBefore:Bool;
	public final pendingShutdownThreadAfter:Bool;
	public final inputDisabled:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
