package codexhx.runtime.tui.smoke;

typedef TuiSmokePermissionSelectionActionFields = {
	final kind:TuiSmokePermissionSelectionActionKind;
	final presetId:String;
	final profileId:String;
	final displayLabel:String;
	final approvalPolicy:String;
	final reviewer:String;
	final selectedId:String;
	final failureCode:String;
	final itemCount:Int;
	final builtinCount:Int;
	final customProfileCount:Int;
	final disabledCount:Int;
	final denialCount:Int;
	final includeReadOnly:Bool;
	final guardianEnabled:Bool;
	final autoReviewIncluded:Bool;
	final windowsDegradedSandbox:Bool;
	final elevateSandboxHint:Bool;
	final isCurrent:Bool;
	final overrideTurnContext:Bool;
	final updateApprovalPolicy:Bool;
	final updateReviewer:Bool;
	final selectProfileEvent:Bool;
	final historyCellEmitted:Bool;
	final warningHidden:Bool;
	final requiresConfirmation:Bool;
	final confirmationOpened:Bool;
	final returnToPermissions:Bool;
	final rememberDismissal:Bool;
	final popupOpened:Bool;
	final emptyInfoInserted:Bool;
	final missingThreadError:Bool;
	final submitThreadOp:Bool;
	final infoInserted:Bool;
	final approvalDisabled:Bool;
	final guardianDisabled:Bool;
	final skippedByNavigation:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noFilesystemMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokePermissionSelectionAction {
	public final kind:TuiSmokePermissionSelectionActionKind;
	public final presetId:String;
	public final profileId:String;
	public final displayLabel:String;
	public final approvalPolicy:String;
	public final reviewer:String;
	public final selectedId:String;
	public final failureCode:String;
	public final itemCount:Int;
	public final builtinCount:Int;
	public final customProfileCount:Int;
	public final disabledCount:Int;
	public final denialCount:Int;
	public final includeReadOnly:Bool;
	public final guardianEnabled:Bool;
	public final autoReviewIncluded:Bool;
	public final windowsDegradedSandbox:Bool;
	public final elevateSandboxHint:Bool;
	public final isCurrent:Bool;
	public final overrideTurnContext:Bool;
	public final updateApprovalPolicy:Bool;
	public final updateReviewer:Bool;
	public final selectProfileEvent:Bool;
	public final historyCellEmitted:Bool;
	public final warningHidden:Bool;
	public final requiresConfirmation:Bool;
	public final confirmationOpened:Bool;
	public final returnToPermissions:Bool;
	public final rememberDismissal:Bool;
	public final popupOpened:Bool;
	public final emptyInfoInserted:Bool;
	public final missingThreadError:Bool;
	public final submitThreadOp:Bool;
	public final infoInserted:Bool;
	public final approvalDisabled:Bool;
	public final guardianDisabled:Bool;
	public final skippedByNavigation:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noFilesystemMutation:Bool;
	public final unsupportedRejected:Bool;
}
