package codexhx.runtime.tui.smoke;

typedef TuiSmokeToolLifecycleActionFields = {
	final kind:TuiSmokeToolLifecycleActionKind;
	final callId:String;
	final itemKind:String;
	final status:String;
	final server:String;
	final tool:String;
	final path:String;
	final changeKind:String;
	final originalCommand:String;
	final displayCommand:String;
	final outputFragment:String;
	final query:String;
	final action:String;
	final resultKind:String;
	final errorMessage:String;
	final revisedPrompt:String;
	final savedPath:String;
	final collabTool:String;
	final collabStatus:String;
	final threadId:String;
	final summary:String;
	final failureCode:String;
	final changeCount:Int;
	final historyCellCount:Int;
	final exitCode:Int;
	final durationMs:Int;
	final queuedStartedCount:Int;
	final queuedCompletedCount:Int;
	final pendingSpawnCountBefore:Int;
	final pendingSpawnCountAfter:Int;
	final activeCellBefore:String;
	final activeCellAfter:String;
	final activeCellMatched:Bool;
	final pathPreserved:Bool;
	final shellWrapperStripped:Bool;
	final outputPreserved:Bool;
	final activeCellFlushed:Bool;
	final answerStreamFlushed:Bool;
	final historyInserted:Bool;
	final extraHistoryInserted:Bool;
	final requestRedraw:Bool;
	final hadWorkActivity:Bool;
	final visibleTurnActivityRecorded:Bool;
	final spawnRequestCached:Bool;
	final spawnRequestRemoved:Bool;
	final queuedToStarted:Bool;
	final queuedToCompleted:Bool;
	final noLiveToolExecution:Bool;
	final noFilesystemMutation:Bool;
	final noNetwork:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeToolLifecycleAction {
	public final kind:TuiSmokeToolLifecycleActionKind;
	public final callId:String;
	public final itemKind:String;
	public final status:String;
	public final server:String;
	public final tool:String;
	public final path:String;
	public final changeKind:String;
	public final originalCommand:String;
	public final displayCommand:String;
	public final outputFragment:String;
	public final query:String;
	public final action:String;
	public final resultKind:String;
	public final errorMessage:String;
	public final revisedPrompt:String;
	public final savedPath:String;
	public final collabTool:String;
	public final collabStatus:String;
	public final threadId:String;
	public final summary:String;
	public final failureCode:String;
	public final changeCount:Int;
	public final historyCellCount:Int;
	public final exitCode:Int;
	public final durationMs:Int;
	public final queuedStartedCount:Int;
	public final queuedCompletedCount:Int;
	public final pendingSpawnCountBefore:Int;
	public final pendingSpawnCountAfter:Int;
	public final activeCellBefore:String;
	public final activeCellAfter:String;
	public final activeCellMatched:Bool;
	public final pathPreserved:Bool;
	public final shellWrapperStripped:Bool;
	public final outputPreserved:Bool;
	public final activeCellFlushed:Bool;
	public final answerStreamFlushed:Bool;
	public final historyInserted:Bool;
	public final extraHistoryInserted:Bool;
	public final requestRedraw:Bool;
	public final hadWorkActivity:Bool;
	public final visibleTurnActivityRecorded:Bool;
	public final spawnRequestCached:Bool;
	public final spawnRequestRemoved:Bool;
	public final queuedToStarted:Bool;
	public final queuedToCompleted:Bool;
	public final noLiveToolExecution:Bool;
	public final noFilesystemMutation:Bool;
	public final noNetwork:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
