package codexhx.runtime.tui.smoke;

typedef TuiSmokeTurnRuntimeActionFields = {
	final kind:TuiSmokeTurnRuntimeActionKind;
	final source:String;
	final status:String;
	final message:String;
	final notificationKind:String;
	final display:String;
	final promptTitle:String;
	final mode:String;
	final contextLabel:String;
	final errorKind:String;
	final failureCode:String;
	final activeGoal:String;
	final agentTurnRunning:Bool;
	final mcpStartupRunning:Bool;
	final taskRunningBefore:Bool;
	final taskRunningAfter:Bool;
	final pendingStartBefore:Bool;
	final pendingStartAfter:Bool;
	final activeHookCellBefore:Bool;
	final activeHookCellAfter:Bool;
	final pendingStatusRestoreBefore:Bool;
	final pendingStatusRestoreAfter:Bool;
	final interruptHintVisible:Bool;
	final terminalTitleWorking:Bool;
	final statusHeaderSet:Bool;
	final transcriptReset:Bool;
	final adaptiveChunkingReset:Bool;
	final planStreamCleared:Bool;
	final runtimeMetricsReset:Bool;
	final telemetryReset:Bool;
	final quitHintCleared:Bool;
	final reasoningCleared:Bool;
	final petKind:String;
	final requestRedraw:Bool;
	final runtimeDelta:String;
	final metricsMerged:Bool;
	final websocketTimingLogged:Bool;
	final historyInserted:Bool;
	final finalSeparatorInserted:Bool;
	final elapsedSeconds:Int;
	final fromReplay:Bool;
	final lastAgentMessage:String;
	final copySource:String;
	final notificationResponse:String;
	final answerStreamFlushed:Bool;
	final planFinalized:Bool;
	final planConsolidated:Bool;
	final waitStreakFlushed:Bool;
	final runtimeMetricsAttached:Bool;
	final statusLineRefreshRequested:Bool;
	final gitSummaryRefreshRequested:Bool;
	final runningCommandsBefore:Int;
	final runningCommandsAfter:Int;
	final suppressedExecBefore:Int;
	final suppressedExecAfter:Int;
	final pendingSteersBefore:Int;
	final pendingSteersAfter:Int;
	final queuedFollowUps:Bool;
	final followUpStarted:Bool;
	final notificationQueued:Bool;
	final pendingPreviewRefreshed:Bool;
	final planPromptEligible:Bool;
	final planSeen:Bool;
	final modalActive:Bool;
	final rateLimitPending:Bool;
	final promptOpened:Bool;
	final rateLimitPromptShown:Bool;
	final warningDisplayed:Bool;
	final warningDeduped:Bool;
	final activeCellFinalized:Bool;
	final activeHookCleared:Bool;
	final streamsCleared:Bool;
	final cancelEditCleared:Bool;
	final queueDrainAttempted:Bool;
	final errorInserted:Bool;
	final cyberPolicy:Bool;
	final ownerNudgeOpened:Bool;
	final planItemsTotal:Int;
	final planItemsCompleted:Int;
	final planProgressRecorded:Bool;
	final allowed:Bool;
	final priority:Int;
	final existingPriority:Int;
	final stored:Bool;
	final posted:Bool;
	final noLiveProcess:Bool;
	final noFilesystemMutation:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeTurnRuntimeAction {
	public final kind:TuiSmokeTurnRuntimeActionKind;
	public final source:String;
	public final status:String;
	public final message:String;
	public final notificationKind:String;
	public final display:String;
	public final promptTitle:String;
	public final mode:String;
	public final contextLabel:String;
	public final errorKind:String;
	public final failureCode:String;
	public final activeGoal:String;
	public final agentTurnRunning:Bool;
	public final mcpStartupRunning:Bool;
	public final taskRunningBefore:Bool;
	public final taskRunningAfter:Bool;
	public final pendingStartBefore:Bool;
	public final pendingStartAfter:Bool;
	public final activeHookCellBefore:Bool;
	public final activeHookCellAfter:Bool;
	public final pendingStatusRestoreBefore:Bool;
	public final pendingStatusRestoreAfter:Bool;
	public final interruptHintVisible:Bool;
	public final terminalTitleWorking:Bool;
	public final statusHeaderSet:Bool;
	public final transcriptReset:Bool;
	public final adaptiveChunkingReset:Bool;
	public final planStreamCleared:Bool;
	public final runtimeMetricsReset:Bool;
	public final telemetryReset:Bool;
	public final quitHintCleared:Bool;
	public final reasoningCleared:Bool;
	public final petKind:String;
	public final requestRedraw:Bool;
	public final runtimeDelta:String;
	public final metricsMerged:Bool;
	public final websocketTimingLogged:Bool;
	public final historyInserted:Bool;
	public final finalSeparatorInserted:Bool;
	public final elapsedSeconds:Int;
	public final fromReplay:Bool;
	public final lastAgentMessage:String;
	public final copySource:String;
	public final notificationResponse:String;
	public final answerStreamFlushed:Bool;
	public final planFinalized:Bool;
	public final planConsolidated:Bool;
	public final waitStreakFlushed:Bool;
	public final runtimeMetricsAttached:Bool;
	public final statusLineRefreshRequested:Bool;
	public final gitSummaryRefreshRequested:Bool;
	public final runningCommandsBefore:Int;
	public final runningCommandsAfter:Int;
	public final suppressedExecBefore:Int;
	public final suppressedExecAfter:Int;
	public final pendingSteersBefore:Int;
	public final pendingSteersAfter:Int;
	public final queuedFollowUps:Bool;
	public final followUpStarted:Bool;
	public final notificationQueued:Bool;
	public final pendingPreviewRefreshed:Bool;
	public final planPromptEligible:Bool;
	public final planSeen:Bool;
	public final modalActive:Bool;
	public final rateLimitPending:Bool;
	public final promptOpened:Bool;
	public final rateLimitPromptShown:Bool;
	public final warningDisplayed:Bool;
	public final warningDeduped:Bool;
	public final activeCellFinalized:Bool;
	public final activeHookCleared:Bool;
	public final streamsCleared:Bool;
	public final cancelEditCleared:Bool;
	public final queueDrainAttempted:Bool;
	public final errorInserted:Bool;
	public final cyberPolicy:Bool;
	public final ownerNudgeOpened:Bool;
	public final planItemsTotal:Int;
	public final planItemsCompleted:Int;
	public final planProgressRecorded:Bool;
	public final allowed:Bool;
	public final priority:Int;
	public final existingPriority:Int;
	public final stored:Bool;
	public final posted:Bool;
	public final noLiveProcess:Bool;
	public final noFilesystemMutation:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
