package codexhx.runtime.tui.smoke;

typedef TuiSmokeStatusSurfaceActionFields = {
	final kind:TuiSmokeStatusSurfaceActionKind;
	final statusLineItems:String;
	final terminalTitleItems:String;
	final invalidStatusLineItems:String;
	final invalidTerminalTitleItems:String;
	final statusLineText:String;
	final statusLineHyperlink:String;
	final terminalTitle:String;
	final lastTerminalTitleBefore:String;
	final lastTerminalTitleAfter:String;
	final statusHeader:String;
	final statusDetails:String;
	final configuredItems:String;
	final originalItems:String;
	final cwd:String;
	final branch:String;
	final gitSummary:String;
	final failureCode:String;
	final statusLineItemCount:Int;
	final terminalTitleItemCount:Int;
	final statusLineSegmentCount:Int;
	final invalidWarningCount:Int;
	final frameDelayMs:Int;
	final threadPresent:Bool;
	final statusLineEnabled:Bool;
	final terminalTitleEmptySelection:Bool;
	final usesGitBranch:Bool;
	final usesGitSummary:Bool;
	final branchReset:Bool;
	final branchRequested:Bool;
	final branchStaleIgnored:Bool;
	final gitSummaryReset:Bool;
	final gitSummaryRequested:Bool;
	final gitSummaryStaleIgnored:Bool;
	final statusInvalidWarningInserted:Bool;
	final statusInvalidWarningSuppressed:Bool;
	final titleInvalidWarningInserted:Bool;
	final titleInvalidWarningSuppressed:Bool;
	final statusLineCleared:Bool;
	final hyperlinkCleared:Bool;
	final terminalTitleCleared:Bool;
	final terminalTitleSkippedDuplicate:Bool;
	final terminalTitleNoVisibleContent:Bool;
	final terminalTitleSet:Bool;
	final frameScheduled:Bool;
	final titleUsesStatus:Bool;
	final statusSurfacesRefreshed:Bool;
	final statusLineSetupCommitted:Bool;
	final statusLineSetupCancelled:Bool;
	final terminalTitlePreviewStarted:Bool;
	final terminalTitlePreviewReverted:Bool;
	final terminalTitleSetupCommitted:Bool;
	final originalSnapshotCleared:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeStatusSurfaceAction {
	public final kind:TuiSmokeStatusSurfaceActionKind;
	public final statusLineItems:String;
	public final terminalTitleItems:String;
	public final invalidStatusLineItems:String;
	public final invalidTerminalTitleItems:String;
	public final statusLineText:String;
	public final statusLineHyperlink:String;
	public final terminalTitle:String;
	public final lastTerminalTitleBefore:String;
	public final lastTerminalTitleAfter:String;
	public final statusHeader:String;
	public final statusDetails:String;
	public final configuredItems:String;
	public final originalItems:String;
	public final cwd:String;
	public final branch:String;
	public final gitSummary:String;
	public final failureCode:String;
	public final statusLineItemCount:Int;
	public final terminalTitleItemCount:Int;
	public final statusLineSegmentCount:Int;
	public final invalidWarningCount:Int;
	public final frameDelayMs:Int;
	public final threadPresent:Bool;
	public final statusLineEnabled:Bool;
	public final terminalTitleEmptySelection:Bool;
	public final usesGitBranch:Bool;
	public final usesGitSummary:Bool;
	public final branchReset:Bool;
	public final branchRequested:Bool;
	public final branchStaleIgnored:Bool;
	public final gitSummaryReset:Bool;
	public final gitSummaryRequested:Bool;
	public final gitSummaryStaleIgnored:Bool;
	public final statusInvalidWarningInserted:Bool;
	public final statusInvalidWarningSuppressed:Bool;
	public final titleInvalidWarningInserted:Bool;
	public final titleInvalidWarningSuppressed:Bool;
	public final statusLineCleared:Bool;
	public final hyperlinkCleared:Bool;
	public final terminalTitleCleared:Bool;
	public final terminalTitleSkippedDuplicate:Bool;
	public final terminalTitleNoVisibleContent:Bool;
	public final terminalTitleSet:Bool;
	public final frameScheduled:Bool;
	public final titleUsesStatus:Bool;
	public final statusSurfacesRefreshed:Bool;
	public final statusLineSetupCommitted:Bool;
	public final statusLineSetupCancelled:Bool;
	public final terminalTitlePreviewStarted:Bool;
	public final terminalTitlePreviewReverted:Bool;
	public final terminalTitleSetupCommitted:Bool;
	public final originalSnapshotCleared:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
