package codexhx.runtime.tui.smoke;

typedef TuiSmokeAppLinkViewActionFields = {
	final kind:TuiSmokeAppLinkViewActionKind;
	final name:String;
	final serverName:String;
	final requestId:String;
	final threadId:String;
	final url:String;
	final elicitationId:String;
	final message:String;
	final hasAuthMeta:Bool;
	final authFailure:Bool;
	final connectorId:String;
	final connectorName:String;
	final appId:String;
	final title:String;
	final description:String;
	final instructions:String;
	final isInstalled:Bool;
	final isEnabled:Bool;
	final suggestionType:String;
	final hasTarget:Bool;
	final screen:String;
	final selectedIndex:Int;
	final direction:String;
	final moveCount:Int;
	final dismissServerName:String;
	final dismissRequestId:String;
	final width:Int;
	final expectedAdmitted:Bool;
	final expectedSummary:String;
	final expectedLabels:Array<String>;
	final expectedRows:Array<String>;
	final expectedSelectedIndex:Int;
	final expectedScreen:String;
	final expectedEnabled:Bool;
	final expectedComplete:Bool;
	final expectedEvents:Array<String>;
	final expectedDismissed:Bool;
	final expectedRequiresTitleAction:Bool;
	final expectedHeight:Int;
	final failureCode:String;
	final noTerminalMutation:Bool;
	final noRatatuiBuffer:Bool;
	final noBrowserLaunch:Bool;
	final noAppServerDelivery:Bool;
	final noFilesystemMutation:Bool;
	final noClipboardMutation:Bool;
	final noNetwork:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeAppLinkViewAction {
	@:recordDefault(TuiSmokeAppLinkViewActionKind.Unknown)
	public final kind:TuiSmokeAppLinkViewActionKind;
	public final name:String;
	public final serverName:String;
	public final requestId:String;
	public final threadId:String;
	public final url:String;
	public final elicitationId:String;
	public final message:String;
	public final hasAuthMeta:Bool;
	public final authFailure:Bool;
	public final connectorId:String;
	public final connectorName:String;
	public final appId:String;
	public final title:String;
	public final description:String;
	public final instructions:String;
	public final isInstalled:Bool;
	public final isEnabled:Bool;
	public final suggestionType:String;
	public final hasTarget:Bool;
	public final screen:String;
	public final selectedIndex:Int;
	public final direction:String;
	public final moveCount:Int;
	public final dismissServerName:String;
	public final dismissRequestId:String;
	public final width:Int;
	public final expectedAdmitted:Bool;
	public final expectedSummary:String;
	public final expectedLabels:Array<String>;
	public final expectedRows:Array<String>;
	public final expectedSelectedIndex:Int;
	public final expectedScreen:String;
	public final expectedEnabled:Bool;
	public final expectedComplete:Bool;
	public final expectedEvents:Array<String>;
	public final expectedDismissed:Bool;
	public final expectedRequiresTitleAction:Bool;
	public final expectedHeight:Int;
	public final failureCode:String;
	public final noTerminalMutation:Bool;
	public final noRatatuiBuffer:Bool;
	public final noBrowserLaunch:Bool;
	public final noAppServerDelivery:Bool;
	public final noFilesystemMutation:Bool;
	public final noClipboardMutation:Bool;
	public final noNetwork:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
