package codexhx.runtime.tui.smoke;

enum abstract TuiSmokeEventKind(String) to String {
	final Draw = "draw";
	final Resize = "resize";
	final ResizeDraw = "resize_draw";
	final Key = "key";
	final StatusUpdate = "status_update";
	final InputUpdate = "input_update";
	final AppExit = "app_exit";
	final EnqueueApp = "enqueue_app";
	final AppServer = "app_server";
	final AppServerRequest = "app_server_request";
	final AppServerResolution = "app_server_resolution";
	final ThreadNotification = "thread_notification";
	final ThreadDelivery = "thread_delivery";
	final ThreadReplay = "thread_replay";
	final EventStream = "event_stream";
	final TerminalMode = "terminal_mode";
	final AltScreen = "alt_screen";
	final DrawComposition = "draw_composition";
	final FrameScheduler = "frame_scheduler";
	final DrawDispatch = "draw_dispatch";
	final OverlayRouting = "overlay_routing";
	final ApprovalOverlay = "approval_overlay";
	final UserInputOverlay = "user_input_overlay";
	final McpElicitationOverlay = "mcp_elicitation_overlay";
	final AppLinkOverlay = "app_link_overlay";
	final HooksBrowser = "hooks_browser";
	final SlashCommandPopup = "slash_command_popup";
	final FileMentionPopup = "file_mention_popup";
	final HistorySearch = "history_search";
	final ComposerAttachment = "composer_attachment";
	final ComposerSubmission = "composer_submission";
	final ComposerEditing = "composer_editing";
	final ComposerPopupSync = "composer_popup_sync";
	final ComposerPopupKey = "composer_popup_key";
	final ComposerPopupRender = "composer_popup_render";
	final ComposerFooterRender = "composer_footer_render";
	final ComposerTextareaRender = "composer_textarea_render";
	final ChatWidgetComposerRender = "chat_widget_composer_render";
	final ChatWidgetActiveStream = "chat_widget_active_stream";
	final ChatWidgetStreamStatus = "chat_widget_stream_status";
	final ChatWidgetStreamLifecycle = "chat_widget_stream_lifecycle";
	final ChatWidgetMcpStartup = "chat_widget_mcp_startup";
	final ChatWidgetStatusSurface = "chat_widget_status_surface";
	final ChatWidgetStatusSurfaceRender = "chat_widget_status_surface_render";
	final ChatWidgetStatusState = "chat_widget_status_state";
	final ChatWidgetCommandLifecycle = "chat_widget_command_lifecycle";
	final ChatWidgetToolLifecycle = "chat_widget_tool_lifecycle";
	final ChatWidgetHookLifecycle = "chat_widget_hook_lifecycle";
	final ChatWidgetInputSubmission = "chat_widget_input_submission";
	final ChatWidgetTurnRuntime = "chat_widget_turn_runtime";
	final ChatWidgetSessionFlow = "chat_widget_session_flow";
	final ChatWidgetReplayProtocol = "chat_widget_replay_protocol";
	final ChatWidgetRateLimit = "chat_widget_rate_limit";
	final ChatWidgetWindowsSandbox = "chat_widget_windows_sandbox";
	final ChatWidgetPermissionSelection = "chat_widget_permission_selection";
	final ChatWidgetModelSettings = "chat_widget_model_settings";
	final GoalDisplay = "goal_display";
	final GitActionDirectives = "git_action_directives";
	final ThreadTranscript = "thread_transcript";
	final LineTruncation = "line_truncation";
	final MarkdownTextMerge = "markdown_text_merge";
	final TextFormatting = "text_formatting";
	final LiveWrap = "live_wrap";
	final Wrapping = "wrapping";
	final ScrollState = "scroll_state";
	final SelectionTabs = "selection_tabs";
	final ActionRequiredTitle = "action_required_title";
	final PopupConsts = "popup_consts";
	final StatusLineStyle = "status_line_style";
	final StatusSurfacePreview = "status_surface_preview";
	final PendingInputPreview = "pending_input_preview";
	final PendingThreadApprovals = "pending_thread_approvals";
	final PromptArgs = "prompt_args";
	final UnifiedExecFooter = "unified_exec_footer";
	final FileSearchPopup = "file_search_popup";
	final SkillPopup = "skill_popup";
	final SelectionPopupCommon = "selection_popup_common";
	final ListSelectionView = "list_selection_view";
	final CommandPopup = "command_popup";
	final ChatWidgetGoalMenu = "chat_widget_goal_menu";
	final ChatWidgetReviewMode = "chat_widget_review_mode";
	final ChatWidgetTranscriptHistory = "chat_widget_transcript_history";
	final ChatWidgetTranscriptOverlay = "chat_widget_transcript_overlay";
	final ChatWidgetBacktrackOverlay = "chat_widget_backtrack_overlay";
	final ChatWidgetKeymapRawOutput = "chat_widget_keymap_raw_output";
	final ChatWidgetRawOutputRender = "chat_widget_raw_output_render";
	final ChatWidgetInterruptQuit = "chat_widget_interrupt_quit";
	final ChatWidgetSlashCommand = "chat_widget_slash_command";
	final ChatWidgetStatusCard = "chat_widget_status_card";
	final ChatWidgetInterruptedRestore = "chat_widget_interrupted_restore";
	final SideConversation = "side_conversation";
	final ClearArchive = "clear_archive";
	final SessionArchiveCommand = "session_archive_command";
	final ResumeFork = "resume_fork";
	final TerminalTitle = "terminal_title";
	final BrowserOpen = "browser_open";
	final DesktopThread = "desktop_thread";
	final TerminalVisualization = "terminal_visualization";
	final AgentStatus = "agent_status";
	final AgentNavigation = "agent_navigation";
	final LoadedThreads = "loaded_threads";
	final DesktopNotification = "desktop_notification";
	final TerminalHyperlink = "terminal_hyperlink";
	final TerminalPaletteProbe = "terminal_palette_probe";
	final TerminalStartupProbe = "terminal_startup_probe";
	final ClipboardCopy = "clipboard_copy";
	final ClipboardPaste = "clipboard_paste";
	final Unknown = "unknown";

	public static function fromString(value:String):TuiSmokeEventKind {
		return switch value {
			case "draw": Draw;
			case "resize": Resize;
			case "resize_draw": ResizeDraw;
			case "key": Key;
			case "status_update": StatusUpdate;
			case "input_update": InputUpdate;
			case "app_exit": AppExit;
			case "enqueue_app": EnqueueApp;
			case "app_server": AppServer;
			case "app_server_request": AppServerRequest;
			case "app_server_resolution": AppServerResolution;
			case "thread_notification": ThreadNotification;
			case "thread_delivery": ThreadDelivery;
			case "thread_replay": ThreadReplay;
			case "event_stream": EventStream;
			case "terminal_mode": TerminalMode;
			case "alt_screen": AltScreen;
			case "draw_composition": DrawComposition;
			case "frame_scheduler": FrameScheduler;
			case "draw_dispatch": DrawDispatch;
			case "overlay_routing": OverlayRouting;
			case "approval_overlay": ApprovalOverlay;
			case "user_input_overlay": UserInputOverlay;
			case "mcp_elicitation_overlay": McpElicitationOverlay;
			case "app_link_overlay": AppLinkOverlay;
			case "hooks_browser": HooksBrowser;
			case "slash_command_popup": SlashCommandPopup;
			case "file_mention_popup": FileMentionPopup;
			case "history_search": HistorySearch;
			case "composer_attachment": ComposerAttachment;
			case "composer_submission": ComposerSubmission;
			case "composer_editing": ComposerEditing;
			case "composer_popup_sync": ComposerPopupSync;
			case "composer_popup_key": ComposerPopupKey;
			case "composer_popup_render": ComposerPopupRender;
			case "composer_footer_render": ComposerFooterRender;
			case "composer_textarea_render": ComposerTextareaRender;
			case "chat_widget_composer_render": ChatWidgetComposerRender;
			case "chat_widget_active_stream": ChatWidgetActiveStream;
			case "chat_widget_stream_status": ChatWidgetStreamStatus;
			case "chat_widget_stream_lifecycle": ChatWidgetStreamLifecycle;
			case "chat_widget_mcp_startup": ChatWidgetMcpStartup;
			case "chat_widget_status_surface": ChatWidgetStatusSurface;
			case "chat_widget_status_surface_render": ChatWidgetStatusSurfaceRender;
			case "chat_widget_status_state": ChatWidgetStatusState;
			case "chat_widget_command_lifecycle": ChatWidgetCommandLifecycle;
			case "chat_widget_tool_lifecycle": ChatWidgetToolLifecycle;
			case "chat_widget_hook_lifecycle": ChatWidgetHookLifecycle;
			case "chat_widget_input_submission": ChatWidgetInputSubmission;
			case "chat_widget_turn_runtime": ChatWidgetTurnRuntime;
			case "chat_widget_session_flow": ChatWidgetSessionFlow;
			case "chat_widget_replay_protocol": ChatWidgetReplayProtocol;
			case "chat_widget_rate_limit": ChatWidgetRateLimit;
			case "chat_widget_windows_sandbox": ChatWidgetWindowsSandbox;
			case "chat_widget_permission_selection": ChatWidgetPermissionSelection;
			case "chat_widget_model_settings": ChatWidgetModelSettings;
			case "goal_display": GoalDisplay;
			case "git_action_directives": GitActionDirectives;
			case "thread_transcript": ThreadTranscript;
			case "line_truncation": LineTruncation;
			case "markdown_text_merge": MarkdownTextMerge;
			case "text_formatting": TextFormatting;
			case "live_wrap": LiveWrap;
			case "wrapping": Wrapping;
			case "scroll_state": ScrollState;
			case "selection_tabs": SelectionTabs;
			case "action_required_title": ActionRequiredTitle;
			case "popup_consts": PopupConsts;
			case "status_line_style": StatusLineStyle;
			case "status_surface_preview": StatusSurfacePreview;
			case "pending_input_preview": PendingInputPreview;
			case "pending_thread_approvals": PendingThreadApprovals;
			case "prompt_args": PromptArgs;
			case "unified_exec_footer": UnifiedExecFooter;
			case "file_search_popup": FileSearchPopup;
			case "skill_popup": SkillPopup;
			case "selection_popup_common": SelectionPopupCommon;
			case "list_selection_view": ListSelectionView;
			case "command_popup": CommandPopup;
			case "chat_widget_goal_menu": ChatWidgetGoalMenu;
			case "chat_widget_review_mode": ChatWidgetReviewMode;
			case "chat_widget_transcript_history": ChatWidgetTranscriptHistory;
			case "chat_widget_transcript_overlay": ChatWidgetTranscriptOverlay;
			case "chat_widget_backtrack_overlay": ChatWidgetBacktrackOverlay;
			case "chat_widget_keymap_raw_output": ChatWidgetKeymapRawOutput;
			case "chat_widget_raw_output_render": ChatWidgetRawOutputRender;
			case "chat_widget_slash_command": ChatWidgetSlashCommand;
			case "chat_widget_status_card": ChatWidgetStatusCard;
			case "chat_widget_interrupt_quit": ChatWidgetInterruptQuit;
			case "chat_widget_interrupted_restore": ChatWidgetInterruptedRestore;
			case "side_conversation": SideConversation;
			case "clear_archive": ClearArchive;
			case "session_archive_command": SessionArchiveCommand;
			case "resume_fork": ResumeFork;
			case "terminal_title": TerminalTitle;
			case "browser_open": BrowserOpen;
			case "desktop_thread": DesktopThread;
			case "terminal_visualization": TerminalVisualization;
			case "agent_status": AgentStatus;
			case "agent_navigation": AgentNavigation;
			case "loaded_threads": LoadedThreads;
			case "desktop_notification": DesktopNotification;
			case "terminal_hyperlink": TerminalHyperlink;
			case "terminal_palette_probe": TerminalPaletteProbe;
			case "terminal_startup_probe": TerminalStartupProbe;
			case "clipboard_copy": ClipboardCopy;
			case "clipboard_paste": ClipboardPaste;
			case _: Unknown;
		}
	}
}
