package codexhx.runtime.tui.smoke;

typedef TuiSmokeHookLifecycleActionFields = {
	final kind:TuiSmokeHookLifecycleActionKind;
	final runId:String;
	final hookName:String;
	final eventKind:String;
	final status:String;
	final output:String;
	final cwd:String;
	final loadedCwd:String;
	final errorMessage:String;
	final browserEntry:String;
	final failureCode:String;
	final activeCellBefore:String;
	final activeCellAfter:String;
	final activeRunCountBefore:Int;
	final activeRunCountAfter:Int;
	final completedRunCountBefore:Int;
	final completedRunCountAfter:Int;
	final historyCellCount:Int;
	final revisionBefore:Int;
	final revisionAfter:Int;
	final timerDelayMs:Int;
	final fetchCount:Int;
	final activeCellPresentBefore:Bool;
	final activeCellPresentAfter:Bool;
	final existingActiveCell:Bool;
	final completedExistingRun:Bool;
	final addedCompletedRun:Bool;
	final createdCompletedCell:Bool;
	final completedCellEmpty:Bool;
	final completedOutputFlushed:Bool;
	final persistentOutputTaken:Bool;
	final activeCellEmpty:Bool;
	final activeCellCleared:Bool;
	final shouldFlush:Bool;
	final historyInserted:Bool;
	final needsFinalSeparator:Bool;
	final answerStreamFlushed:Bool;
	final visibleTurnActivityRecorded:Bool;
	final requestRedraw:Bool;
	final advancedVisibility:Bool;
	final finishIdle:Bool;
	final frameScheduled:Bool;
	final visibleRunningRun:Bool;
	final deadlineScheduled:Bool;
	final staleCwdIgnored:Bool;
	final errorInserted:Bool;
	final browserOpened:Bool;
	final fetchRequested:Bool;
	final noLiveHookExecution:Bool;
	final noFilesystemMutation:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeHookLifecycleAction {
	public final kind:TuiSmokeHookLifecycleActionKind;
	public final runId:String;
	public final hookName:String;
	public final eventKind:String;
	public final status:String;
	public final output:String;
	public final cwd:String;
	public final loadedCwd:String;
	public final errorMessage:String;
	public final browserEntry:String;
	public final failureCode:String;
	public final activeCellBefore:String;
	public final activeCellAfter:String;
	public final activeRunCountBefore:Int;
	public final activeRunCountAfter:Int;
	public final completedRunCountBefore:Int;
	public final completedRunCountAfter:Int;
	public final historyCellCount:Int;
	public final revisionBefore:Int;
	public final revisionAfter:Int;
	public final timerDelayMs:Int;
	public final fetchCount:Int;
	public final activeCellPresentBefore:Bool;
	public final activeCellPresentAfter:Bool;
	public final existingActiveCell:Bool;
	public final completedExistingRun:Bool;
	public final addedCompletedRun:Bool;
	public final createdCompletedCell:Bool;
	public final completedCellEmpty:Bool;
	public final completedOutputFlushed:Bool;
	public final persistentOutputTaken:Bool;
	public final activeCellEmpty:Bool;
	public final activeCellCleared:Bool;
	public final shouldFlush:Bool;
	public final historyInserted:Bool;
	public final needsFinalSeparator:Bool;
	public final answerStreamFlushed:Bool;
	public final visibleTurnActivityRecorded:Bool;
	public final requestRedraw:Bool;
	public final advancedVisibility:Bool;
	public final finishIdle:Bool;
	public final frameScheduled:Bool;
	public final visibleRunningRun:Bool;
	public final deadlineScheduled:Bool;
	public final staleCwdIgnored:Bool;
	public final errorInserted:Bool;
	public final browserOpened:Bool;
	public final fetchRequested:Bool;
	public final noLiveHookExecution:Bool;
	public final noFilesystemMutation:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
