package codexhx.runtime.tui.smoke;

typedef TuiSmokeChatWidgetInterruptedRestoreActionFields = {
	final kind:TuiSmokeChatWidgetInterruptedRestoreActionKind;
	final reason:String;
	final noticeMode:String;
	final noticeText:String;
	final failureCode:String;
	final promptText:String;
	final restoredText:String;
	final composerText:String;
	final queuedMessagesBefore:Int;
	final queuedMessagesAfter:Int;
	final pendingSteersBefore:Int;
	final pendingSteersAfter:Int;
	final rejectedSteersBefore:Int;
	final rejectedSteersAfter:Int;
	final remoteImageCount:Int;
	final localImageCount:Int;
	final mentionBindingCount:Int;
	final cancelEditEligibleBefore:Bool;
	final cancelEditEligibleAfter:Bool;
	final cancelEditArmedBefore:Bool;
	final cancelEditArmedAfter:Bool;
	final cancelEditPromptBefore:Bool;
	final cancelEditPromptAfter:Bool;
	final composerEmpty:Bool;
	final sideConversationActive:Bool;
	final sendPendingSteersImmediately:Bool;
	final submitPendingSteersAfterInterruptBefore:Bool;
	final submitPendingSteersAfterInterruptAfter:Bool;
	final finalizedTurn:Bool;
	final noticeInserted:Bool;
	final noticeSuppressed:Bool;
	final pendingMerged:Bool;
	final queuedMerged:Bool;
	final composerMerged:Bool;
	final composerRestored:Bool;
	final cancelledTurnRestoreEventSent:Bool;
	final pendingPreviewRefreshed:Bool;
	final threadRollbackSent:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

class TuiSmokeChatWidgetInterruptedRestoreAction {
	public final kind:TuiSmokeChatWidgetInterruptedRestoreActionKind;
	public final reason:String;
	public final noticeMode:String;
	public final noticeText:String;
	public final failureCode:String;
	public final promptText:String;
	public final restoredText:String;
	public final composerText:String;
	public final queuedMessagesBefore:Int;
	public final queuedMessagesAfter:Int;
	public final pendingSteersBefore:Int;
	public final pendingSteersAfter:Int;
	public final rejectedSteersBefore:Int;
	public final rejectedSteersAfter:Int;
	public final remoteImageCount:Int;
	public final localImageCount:Int;
	public final mentionBindingCount:Int;
	public final cancelEditEligibleBefore:Bool;
	public final cancelEditEligibleAfter:Bool;
	public final cancelEditArmedBefore:Bool;
	public final cancelEditArmedAfter:Bool;
	public final cancelEditPromptBefore:Bool;
	public final cancelEditPromptAfter:Bool;
	public final composerEmpty:Bool;
	public final sideConversationActive:Bool;
	public final sendPendingSteersImmediately:Bool;
	public final submitPendingSteersAfterInterruptBefore:Bool;
	public final submitPendingSteersAfterInterruptAfter:Bool;
	public final finalizedTurn:Bool;
	public final noticeInserted:Bool;
	public final noticeSuppressed:Bool;
	public final pendingMerged:Bool;
	public final queuedMerged:Bool;
	public final composerMerged:Bool;
	public final composerRestored:Bool;
	public final cancelledTurnRestoreEventSent:Bool;
	public final pendingPreviewRefreshed:Bool;
	public final threadRollbackSent:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;

	public function new(fields:TuiSmokeChatWidgetInterruptedRestoreActionFields) {
		this.kind = fields.kind == null ? TuiSmokeChatWidgetInterruptedRestoreActionKind.Unknown : fields.kind;
		this.reason = fields.reason == null ? "" : fields.reason;
		this.noticeMode = fields.noticeMode == null ? "" : fields.noticeMode;
		this.noticeText = fields.noticeText == null ? "" : fields.noticeText;
		this.failureCode = fields.failureCode == null ? "" : fields.failureCode;
		this.promptText = fields.promptText == null ? "" : fields.promptText;
		this.restoredText = fields.restoredText == null ? "" : fields.restoredText;
		this.composerText = fields.composerText == null ? "" : fields.composerText;
		this.queuedMessagesBefore = fields.queuedMessagesBefore;
		this.queuedMessagesAfter = fields.queuedMessagesAfter;
		this.pendingSteersBefore = fields.pendingSteersBefore;
		this.pendingSteersAfter = fields.pendingSteersAfter;
		this.rejectedSteersBefore = fields.rejectedSteersBefore;
		this.rejectedSteersAfter = fields.rejectedSteersAfter;
		this.remoteImageCount = fields.remoteImageCount;
		this.localImageCount = fields.localImageCount;
		this.mentionBindingCount = fields.mentionBindingCount;
		this.cancelEditEligibleBefore = fields.cancelEditEligibleBefore;
		this.cancelEditEligibleAfter = fields.cancelEditEligibleAfter;
		this.cancelEditArmedBefore = fields.cancelEditArmedBefore;
		this.cancelEditArmedAfter = fields.cancelEditArmedAfter;
		this.cancelEditPromptBefore = fields.cancelEditPromptBefore;
		this.cancelEditPromptAfter = fields.cancelEditPromptAfter;
		this.composerEmpty = fields.composerEmpty;
		this.sideConversationActive = fields.sideConversationActive;
		this.sendPendingSteersImmediately = fields.sendPendingSteersImmediately;
		this.submitPendingSteersAfterInterruptBefore = fields.submitPendingSteersAfterInterruptBefore;
		this.submitPendingSteersAfterInterruptAfter = fields.submitPendingSteersAfterInterruptAfter;
		this.finalizedTurn = fields.finalizedTurn;
		this.noticeInserted = fields.noticeInserted;
		this.noticeSuppressed = fields.noticeSuppressed;
		this.pendingMerged = fields.pendingMerged;
		this.queuedMerged = fields.queuedMerged;
		this.composerMerged = fields.composerMerged;
		this.composerRestored = fields.composerRestored;
		this.cancelledTurnRestoreEventSent = fields.cancelledTurnRestoreEventSent;
		this.pendingPreviewRefreshed = fields.pendingPreviewRefreshed;
		this.threadRollbackSent = fields.threadRollbackSent;
		this.requestRedraw = fields.requestRedraw;
		this.noLiveTerminal = fields.noLiveTerminal;
		this.noRatatuiRender = fields.noRatatuiRender;
		this.noModelCall = fields.noModelCall;
		this.unsupportedRejected = fields.unsupportedRejected;
	}
}
