package codexhx.runtime.tui.smoke;

typedef TuiSmokeRateLimitActionFields = {
	final kind:TuiSmokeRateLimitActionKind;
	final source:String;
	final limitId:String;
	final label:String;
	final fallbackLabel:String;
	final promptStateBefore:String;
	final promptStateAfter:String;
	final model:String;
	final nudgeModel:String;
	final planTypeBefore:String;
	final planTypeAfter:String;
	final reachedType:String;
	final errorKind:String;
	final errorMessage:String;
	final failureCode:String;
	final windowMinutes:Int;
	final usedPercent:Int;
	final thresholdPercent:Int;
	final remainingPercent:Int;
	final warningCount:Int;
	final primaryIndexBefore:Int;
	final primaryIndexAfter:Int;
	final secondaryIndexBefore:Int;
	final secondaryIndexAfter:Int;
	final entriesBefore:Int;
	final entriesAfter:Int;
	final capReached:Bool;
	final warningEmitted:Bool;
	final creditsPreserved:Bool;
	final individualLimitPreserved:Bool;
	final planTypePreserved:Bool;
	final codexReachedTypeStored:Bool;
	final promptPending:Bool;
	final promptShown:Bool;
	final hiddenNotice:Bool;
	final lowerCostModel:Bool;
	final nonCodexLimit:Bool;
	final taskRunning:Bool;
	final deferred:Bool;
	final shownOnce:Bool;
	final popupOpened:Bool;
	final rateLimitRefreshRequested:Bool;
	final staleCreditsRemapped:Bool;
	final ownerNudgeSuppressed:Bool;
	final missingStateSuppressed:Bool;
	final classified:Bool;
	final cyberPolicy:Bool;
	final noLiveAccountRefresh:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeRateLimitAction {
	public final kind:TuiSmokeRateLimitActionKind;
	public final source:String;
	public final limitId:String;
	public final label:String;
	public final fallbackLabel:String;
	public final promptStateBefore:String;
	public final promptStateAfter:String;
	public final model:String;
	public final nudgeModel:String;
	public final planTypeBefore:String;
	public final planTypeAfter:String;
	public final reachedType:String;
	public final errorKind:String;
	public final errorMessage:String;
	public final failureCode:String;
	public final windowMinutes:Int;
	public final usedPercent:Int;
	public final thresholdPercent:Int;
	public final remainingPercent:Int;
	public final warningCount:Int;
	public final primaryIndexBefore:Int;
	public final primaryIndexAfter:Int;
	public final secondaryIndexBefore:Int;
	public final secondaryIndexAfter:Int;
	public final entriesBefore:Int;
	public final entriesAfter:Int;
	public final capReached:Bool;
	public final warningEmitted:Bool;
	public final creditsPreserved:Bool;
	public final individualLimitPreserved:Bool;
	public final planTypePreserved:Bool;
	public final codexReachedTypeStored:Bool;
	public final promptPending:Bool;
	public final promptShown:Bool;
	public final hiddenNotice:Bool;
	public final lowerCostModel:Bool;
	public final nonCodexLimit:Bool;
	public final taskRunning:Bool;
	public final deferred:Bool;
	public final shownOnce:Bool;
	public final popupOpened:Bool;
	public final rateLimitRefreshRequested:Bool;
	public final staleCreditsRemapped:Bool;
	public final ownerNudgeSuppressed:Bool;
	public final missingStateSuppressed:Bool;
	public final classified:Bool;
	public final cyberPolicy:Bool;
	public final noLiveAccountRefresh:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
