package codexhx.runtime.tui.smoke;

typedef TuiSmokeReviewModeActionFields = {
	final kind:TuiSmokeReviewModeActionKind;
	final target:String;
	final hint:String;
	final pickerKind:String;
	final prompt:String;
	final guardianStatus:String;
	final risk:String;
	final actionSummary:String;
	final statusHeader:String;
	final statusDetails:String;
	final failureCode:String;
	final itemCount:Int;
	final branchCount:Int;
	final commitCount:Int;
	final pendingSteerCount:Int;
	final queuedMessageCount:Int;
	final rejectedSteerCount:Int;
	final submittedCount:Int;
	final preReviewPercent:Int;
	final reviewPercent:Int;
	final restoredPercent:Int;
	final parallelCount:Int;
	final remainingCount:Int;
	final popupOpened:Bool;
	final branchPickerEvent:Bool;
	final commitPickerEvent:Bool;
	final uncommittedReviewEvent:Bool;
	final customPromptEvent:Bool;
	final dismissParentOnChildAccept:Bool;
	final searchable:Bool;
	final emptyIgnored:Bool;
	final reviewModeEntered:Bool;
	final reviewModeExited:Bool;
	final bannerInserted:Bool;
	final reviewPromptSuppressed:Bool;
	final assistantRendered:Bool;
	final pendingSteerSubmitted:Bool;
	final nonSteerableRejected:Bool;
	final rejectedSteersPrepended:Bool;
	final mergedAfterReviewExit:Bool;
	final existingQueuePreserved:Bool;
	final escWarningInserted:Bool;
	final interruptSuppressed:Bool;
	final tokenSnapshotSaved:Bool;
	final tokenRestored:Bool;
	final statusSet:Bool;
	final historyInserted:Bool;
	final warningInserted:Bool;
	final denialStored:Bool;
	final approvalSubmitted:Bool;
	final remainingStatusVisible:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noAppServerMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeReviewModeAction {
	public final kind:TuiSmokeReviewModeActionKind;
	public final target:String;
	public final hint:String;
	public final pickerKind:String;
	public final prompt:String;
	public final guardianStatus:String;
	public final risk:String;
	public final actionSummary:String;
	public final statusHeader:String;
	public final statusDetails:String;
	public final failureCode:String;
	public final itemCount:Int;
	public final branchCount:Int;
	public final commitCount:Int;
	public final pendingSteerCount:Int;
	public final queuedMessageCount:Int;
	public final rejectedSteerCount:Int;
	public final submittedCount:Int;
	public final preReviewPercent:Int;
	public final reviewPercent:Int;
	public final restoredPercent:Int;
	public final parallelCount:Int;
	public final remainingCount:Int;
	public final popupOpened:Bool;
	public final branchPickerEvent:Bool;
	public final commitPickerEvent:Bool;
	public final uncommittedReviewEvent:Bool;
	public final customPromptEvent:Bool;
	public final dismissParentOnChildAccept:Bool;
	public final searchable:Bool;
	public final emptyIgnored:Bool;
	public final reviewModeEntered:Bool;
	public final reviewModeExited:Bool;
	public final bannerInserted:Bool;
	public final reviewPromptSuppressed:Bool;
	public final assistantRendered:Bool;
	public final pendingSteerSubmitted:Bool;
	public final nonSteerableRejected:Bool;
	public final rejectedSteersPrepended:Bool;
	public final mergedAfterReviewExit:Bool;
	public final existingQueuePreserved:Bool;
	public final escWarningInserted:Bool;
	public final interruptSuppressed:Bool;
	public final tokenSnapshotSaved:Bool;
	public final tokenRestored:Bool;
	public final statusSet:Bool;
	public final historyInserted:Bool;
	public final warningInserted:Bool;
	public final denialStored:Bool;
	public final approvalSubmitted:Bool;
	public final remainingStatusVisible:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noAppServerMutation:Bool;
	public final unsupportedRejected:Bool;
}
