package codexhx.runtime.tui.smoke;

typedef TuiSmokeInputSubmissionActionFields = {
	final kind:TuiSmokeInputSubmissionActionKind;
	final text:String;
	final action:String;
	final source:String;
	final historyRecord:String;
	final shellCommand:String;
	final model:String;
	final collaborationMode:String;
	final errorMessage:String;
	final failureCode:String;
	final previewText:String;
	final itemsSummary:String;
	final mentionsSummary:String;
	final localImages:Int;
	final remoteImages:Int;
	final textElements:Int;
	final mentionBindings:Int;
	final queuedBefore:Int;
	final queuedAfter:Int;
	final pendingSteersBefore:Int;
	final pendingSteersAfter:Int;
	final rejectedBefore:Int;
	final rejectedAfter:Int;
	final historyBefore:Int;
	final historyAfter:Int;
	final itemsCount:Int;
	final skillsCount:Int;
	final pluginsCount:Int;
	final appsCount:Int;
	final duplicatesSkipped:Int;
	final budgetCountBefore:Int;
	final budgetCountAfter:Int;
	final sessionConfigured:Bool;
	final planStreaming:Bool;
	final taskRunning:Bool;
	final agentTurnRunningBefore:Bool;
	final agentTurnRunningAfter:Bool;
	final sleepTurnRunningBefore:Bool;
	final sleepTurnRunningAfter:Bool;
	final preventIdleSleep:Bool;
	final queued:Bool;
	final submitted:Bool;
	final accepted:Bool;
	final appCommandCreated:Bool;
	final pendingPreviewRefreshed:Bool;
	final reasoningCleared:Bool;
	final statusSet:Bool;
	final emptyRejected:Bool;
	final modelSupportsImages:Bool;
	final restoredComposer:Bool;
	final warningInserted:Bool;
	final requestRedraw:Bool;
	final shellEscapeAllowed:Bool;
	final shellHelpInserted:Bool;
	final shellRunCommand:Bool;
	final shellHistoryInserted:Bool;
	final renderInHistory:Bool;
	final userTurnPendingStart:Bool;
	final cancelEditRecorded:Bool;
	final displayInserted:Bool;
	final finalSeparatorCleared:Bool;
	final pendingSteerCreated:Bool;
	final historyAppended:Bool;
	final mentionsEncoded:Bool;
	final ideContextApplied:Bool;
	final modelAvailable:Bool;
	final blocked:Bool;
	final noLiveProcess:Bool;
	final noFilesystemMutation:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeInputSubmissionAction {
	public final kind:TuiSmokeInputSubmissionActionKind;
	public final text:String;
	public final action:String;
	public final source:String;
	public final historyRecord:String;
	public final shellCommand:String;
	public final model:String;
	public final collaborationMode:String;
	public final errorMessage:String;
	public final failureCode:String;
	public final previewText:String;
	public final itemsSummary:String;
	public final mentionsSummary:String;
	public final localImages:Int;
	public final remoteImages:Int;
	public final textElements:Int;
	public final mentionBindings:Int;
	public final queuedBefore:Int;
	public final queuedAfter:Int;
	public final pendingSteersBefore:Int;
	public final pendingSteersAfter:Int;
	public final rejectedBefore:Int;
	public final rejectedAfter:Int;
	public final historyBefore:Int;
	public final historyAfter:Int;
	public final itemsCount:Int;
	public final skillsCount:Int;
	public final pluginsCount:Int;
	public final appsCount:Int;
	public final duplicatesSkipped:Int;
	public final budgetCountBefore:Int;
	public final budgetCountAfter:Int;
	public final sessionConfigured:Bool;
	public final planStreaming:Bool;
	public final taskRunning:Bool;
	public final agentTurnRunningBefore:Bool;
	public final agentTurnRunningAfter:Bool;
	public final sleepTurnRunningBefore:Bool;
	public final sleepTurnRunningAfter:Bool;
	public final preventIdleSleep:Bool;
	public final queued:Bool;
	public final submitted:Bool;
	public final accepted:Bool;
	public final appCommandCreated:Bool;
	public final pendingPreviewRefreshed:Bool;
	public final reasoningCleared:Bool;
	public final statusSet:Bool;
	public final emptyRejected:Bool;
	public final modelSupportsImages:Bool;
	public final restoredComposer:Bool;
	public final warningInserted:Bool;
	public final requestRedraw:Bool;
	public final shellEscapeAllowed:Bool;
	public final shellHelpInserted:Bool;
	public final shellRunCommand:Bool;
	public final shellHistoryInserted:Bool;
	public final renderInHistory:Bool;
	public final userTurnPendingStart:Bool;
	public final cancelEditRecorded:Bool;
	public final displayInserted:Bool;
	public final finalSeparatorCleared:Bool;
	public final pendingSteerCreated:Bool;
	public final historyAppended:Bool;
	public final mentionsEncoded:Bool;
	public final ideContextApplied:Bool;
	public final modelAvailable:Bool;
	public final blocked:Bool;
	public final noLiveProcess:Bool;
	public final noFilesystemMutation:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;
}
