package codexhx.runtime.tui.smoke;

typedef TuiSmokeEventFields = {
	final kind:TuiSmokeEventKind;
	final key:TuiSmokeKeyKind;
	final status:String;
	final input:String;
	final exitMode:TuiSmokeExitMode;
	final resizeDraw:Null<TuiSmokeResizeDrawAction>;
	final appEvent:Null<TuiSmokeAppEvent>;
	final appServerEvent:Null<TuiSmokeAppServerEvent>;
	final appServerRequest:Null<TuiSmokeAppServerRequest>;
	final appServerResolution:Null<TuiSmokeAppServerResolution>;
	final threadNotification:Null<TuiSmokeThreadNotification>;
	final threadDelivery:Null<TuiSmokeThreadDeliveryAction>;
	final threadReplay:Null<TuiSmokeThreadReplayAction>;
	final eventStream:Null<TuiSmokeEventStreamPlan>;
	final terminalModePlan:Null<TuiSmokeTerminalModePlan>;
	final altScreen:Null<TuiSmokeAltScreenPlan>;
	final drawComposition:Null<TuiSmokeDrawCompositionPlan>;
	final frameScheduler:Null<TuiSmokeFrameSchedulerPlan>;
	final drawDispatch:Null<TuiSmokeDrawDispatchPlan>;
	final overlayRouting:Null<TuiSmokeOverlayRoutingPlan>;
	final approvalOverlay:Null<TuiSmokeApprovalPlan>;
	final userInputOverlay:Null<TuiSmokeUserInputPlan>;
	final mcpElicitationOverlay:Null<TuiSmokeMcpElicitationPlan>;
	final appLinkOverlay:Null<TuiSmokeAppLinkPlan>;
	final hooksBrowser:Null<TuiSmokeHooksBrowserPlan>;
	final slashCommandPopup:Null<TuiSmokeSlashPopupPlan>;
	final fileMentionPopup:Null<TuiSmokeFileMentionPopupPlan>;
	final historySearch:Null<TuiSmokeHistorySearchPlan>;
	final composerAttachment:Null<TuiSmokeComposerAttachmentPlan>;
	final composerSubmission:Null<TuiSmokeComposerSubmissionPlan>;
	final composerEditing:Null<TuiSmokeComposerEditingPlan>;
	final composerPopupSync:Null<TuiSmokeComposerPopupSyncPlan>;
	final composerPopupKey:Null<TuiSmokeComposerPopupKeyPlan>;
	final composerPopupRender:Null<TuiSmokeComposerPopupRenderPlan>;
	final composerFooterRender:Null<TuiSmokeComposerFooterRenderPlan>;
	final composerTextareaRender:Null<TuiSmokeComposerTextareaRenderPlan>;
	final chatWidgetComposerRender:Null<TuiSmokeChatWidgetComposerRenderPlan>;
	final chatWidgetActiveStream:Null<TuiSmokeChatWidgetActiveStreamPlan>;
	final chatWidgetStreamStatus:Null<TuiSmokeChatWidgetStreamStatusPlan>;
	final chatWidgetStreamLifecycle:Null<TuiSmokeChatWidgetStreamLifecyclePlan>;
	final chatWidgetMcpStartup:Null<TuiSmokeMcpStartupPlan>;
	final chatWidgetStatusSurface:Null<TuiSmokeStatusSurfacePlan>;
	final chatWidgetStatusSurfaceRender:Null<TuiSmokeStatusSurfaceRenderPlan>;
	final chatWidgetStatusState:Null<TuiSmokeStatusStatePlan>;
	final chatWidgetCommandLifecycle:Null<TuiSmokeCommandLifecyclePlan>;
	final chatWidgetToolLifecycle:Null<TuiSmokeToolLifecyclePlan>;
	final chatWidgetHookLifecycle:Null<TuiSmokeHookLifecyclePlan>;
	final chatWidgetInputSubmission:Null<TuiSmokeInputSubmissionPlan>;
	final chatWidgetTurnRuntime:Null<TuiSmokeTurnRuntimePlan>;
	final chatWidgetSessionFlow:Null<TuiSmokeSessionFlowPlan>;
	final chatWidgetReplayProtocol:Null<TuiSmokeReplayProtocolPlan>;
	final chatWidgetRateLimit:Null<TuiSmokeRateLimitPlan>;
	final chatWidgetWindowsSandbox:Null<TuiSmokeWindowsSandboxPlan>;
	final chatWidgetPermissionSelection:Null<TuiSmokePermissionSelectionPlan>;
	final chatWidgetModelSettings:Null<TuiSmokeModelSettingsPlan>;
	final goalDisplay:Null<TuiSmokeGoalDisplayPlan>;
	final gitActionDirectives:Null<TuiSmokeGitActionDirectivePlan>;
	final threadTranscript:Null<TuiSmokeThreadTranscriptPlan>;
	final lineTruncation:Null<TuiSmokeLineTruncationPlan>;
	final markdownTextMerge:Null<TuiSmokeMarkdownTextMergePlan>;
	final textFormatting:Null<TuiSmokeTextFormattingPlan>;
	final chatWidgetGoalMenu:Null<TuiSmokeGoalMenuPlan>;
	final chatWidgetReviewMode:Null<TuiSmokeReviewModePlan>;
	final chatWidgetTranscriptHistory:Null<TuiSmokeTranscriptHistoryPlan>;
	final chatWidgetTranscriptOverlay:Null<TuiSmokeTranscriptOverlayPlan>;
	final chatWidgetBacktrackOverlay:Null<TuiSmokeBacktrackOverlayPlan>;
	final chatWidgetKeymapRawOutput:Null<TuiSmokeKeymapRawOutputPlan>;
	final chatWidgetRawOutputRender:Null<TuiSmokeRawOutputRenderPlan>;
	final chatWidgetSlashCommand:Null<TuiSmokeSlashCommandPlan>;
	final chatWidgetStatusCard:Null<TuiSmokeStatusCardPlan>;
	final chatWidgetInterruptQuit:Null<TuiSmokeChatWidgetInterruptQuitPlan>;
	final chatWidgetInterruptedRestore:Null<TuiSmokeChatWidgetInterruptedRestorePlan>;
	final sideConversation:Null<TuiSmokeSideConversationPlan>;
	final clearArchive:Null<TuiSmokeClearArchivePlan>;
	final sessionArchiveCommand:Null<TuiSmokeSessionArchiveCommandPlan>;
	final resumeFork:Null<TuiSmokeResumeForkPlan>;
	final terminalTitle:Null<TuiSmokeTerminalTitlePlan>;
	final browserOpen:Null<TuiSmokeBrowserOpenPlan>;
	final desktopThread:Null<TuiSmokeDesktopThreadPlan>;
	final terminalVisualization:Null<TuiSmokeTerminalVisualizationPlan>;
	final agentStatus:Null<TuiSmokeAgentStatusPlan>;
	final agentNavigation:Null<TuiSmokeAgentNavigationPlan>;
	final loadedThreads:Null<TuiSmokeLoadedThreadsPlan>;
	final desktopNotification:Null<TuiSmokeDesktopNotificationPlan>;
	final terminalHyperlink:Null<TuiSmokeTerminalHyperlinkPlan>;
	final terminalPalette:Null<TuiSmokeTerminalPalettePlan>;
	final terminalStartupProbe:Null<TuiSmokeTerminalStartupProbePlan>;
	final clipboardCopy:Null<TuiSmokeClipboardCopyPlan>;
	final clipboardPaste:Null<TuiSmokeClipboardPastePlan>;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeEvent {
	@:recordDefault(TuiSmokeEventKind.Unknown)
	public final kind:TuiSmokeEventKind;
	@:recordDefault(TuiSmokeKeyKind.Unknown)
	public final key:TuiSmokeKeyKind;
	public final status:String;
	public final input:String;
	@:recordDefault(TuiSmokeExitMode.Unknown)
	public final exitMode:TuiSmokeExitMode;
	public final resizeDraw:Null<TuiSmokeResizeDrawAction>;
	public final appEvent:Null<TuiSmokeAppEvent>;
	public final appServerEvent:Null<TuiSmokeAppServerEvent>;
	public final appServerRequest:Null<TuiSmokeAppServerRequest>;
	public final appServerResolution:Null<TuiSmokeAppServerResolution>;
	public final threadNotification:Null<TuiSmokeThreadNotification>;
	public final threadDelivery:Null<TuiSmokeThreadDeliveryAction>;
	public final threadReplay:Null<TuiSmokeThreadReplayAction>;
	public final eventStream:Null<TuiSmokeEventStreamPlan>;
	public final terminalModePlan:Null<TuiSmokeTerminalModePlan>;
	public final altScreen:Null<TuiSmokeAltScreenPlan>;
	public final drawComposition:Null<TuiSmokeDrawCompositionPlan>;
	public final frameScheduler:Null<TuiSmokeFrameSchedulerPlan>;
	public final drawDispatch:Null<TuiSmokeDrawDispatchPlan>;
	public final overlayRouting:Null<TuiSmokeOverlayRoutingPlan>;
	public final approvalOverlay:Null<TuiSmokeApprovalPlan>;
	public final userInputOverlay:Null<TuiSmokeUserInputPlan>;
	public final mcpElicitationOverlay:Null<TuiSmokeMcpElicitationPlan>;
	public final appLinkOverlay:Null<TuiSmokeAppLinkPlan>;
	public final hooksBrowser:Null<TuiSmokeHooksBrowserPlan>;
	public final slashCommandPopup:Null<TuiSmokeSlashPopupPlan>;
	public final fileMentionPopup:Null<TuiSmokeFileMentionPopupPlan>;
	public final historySearch:Null<TuiSmokeHistorySearchPlan>;
	public final composerAttachment:Null<TuiSmokeComposerAttachmentPlan>;
	public final composerSubmission:Null<TuiSmokeComposerSubmissionPlan>;
	public final composerEditing:Null<TuiSmokeComposerEditingPlan>;
	public final composerPopupSync:Null<TuiSmokeComposerPopupSyncPlan>;
	public final composerPopupKey:Null<TuiSmokeComposerPopupKeyPlan>;
	public final composerPopupRender:Null<TuiSmokeComposerPopupRenderPlan>;
	public final composerFooterRender:Null<TuiSmokeComposerFooterRenderPlan>;
	public final composerTextareaRender:Null<TuiSmokeComposerTextareaRenderPlan>;
	public final chatWidgetComposerRender:Null<TuiSmokeChatWidgetComposerRenderPlan>;
	public final chatWidgetActiveStream:Null<TuiSmokeChatWidgetActiveStreamPlan>;
	public final chatWidgetStreamStatus:Null<TuiSmokeChatWidgetStreamStatusPlan>;
	public final chatWidgetStreamLifecycle:Null<TuiSmokeChatWidgetStreamLifecyclePlan>;
	public final chatWidgetMcpStartup:Null<TuiSmokeMcpStartupPlan>;
	public final chatWidgetStatusSurface:Null<TuiSmokeStatusSurfacePlan>;
	public final chatWidgetStatusSurfaceRender:Null<TuiSmokeStatusSurfaceRenderPlan>;
	public final chatWidgetStatusState:Null<TuiSmokeStatusStatePlan>;
	public final chatWidgetCommandLifecycle:Null<TuiSmokeCommandLifecyclePlan>;
	public final chatWidgetToolLifecycle:Null<TuiSmokeToolLifecyclePlan>;
	public final chatWidgetHookLifecycle:Null<TuiSmokeHookLifecyclePlan>;
	public final chatWidgetInputSubmission:Null<TuiSmokeInputSubmissionPlan>;
	public final chatWidgetTurnRuntime:Null<TuiSmokeTurnRuntimePlan>;
	public final chatWidgetSessionFlow:Null<TuiSmokeSessionFlowPlan>;
	public final chatWidgetReplayProtocol:Null<TuiSmokeReplayProtocolPlan>;
	public final chatWidgetRateLimit:Null<TuiSmokeRateLimitPlan>;
	public final chatWidgetWindowsSandbox:Null<TuiSmokeWindowsSandboxPlan>;
	public final chatWidgetPermissionSelection:Null<TuiSmokePermissionSelectionPlan>;
	public final chatWidgetModelSettings:Null<TuiSmokeModelSettingsPlan>;
	public final goalDisplay:Null<TuiSmokeGoalDisplayPlan>;
	public final gitActionDirectives:Null<TuiSmokeGitActionDirectivePlan>;
	public final threadTranscript:Null<TuiSmokeThreadTranscriptPlan>;
	public final lineTruncation:Null<TuiSmokeLineTruncationPlan>;
	public final markdownTextMerge:Null<TuiSmokeMarkdownTextMergePlan>;
	public final textFormatting:Null<TuiSmokeTextFormattingPlan>;
	public final chatWidgetGoalMenu:Null<TuiSmokeGoalMenuPlan>;
	public final chatWidgetReviewMode:Null<TuiSmokeReviewModePlan>;
	public final chatWidgetTranscriptHistory:Null<TuiSmokeTranscriptHistoryPlan>;
	public final chatWidgetTranscriptOverlay:Null<TuiSmokeTranscriptOverlayPlan>;
	public final chatWidgetBacktrackOverlay:Null<TuiSmokeBacktrackOverlayPlan>;
	public final chatWidgetKeymapRawOutput:Null<TuiSmokeKeymapRawOutputPlan>;
	public final chatWidgetRawOutputRender:Null<TuiSmokeRawOutputRenderPlan>;
	public final chatWidgetSlashCommand:Null<TuiSmokeSlashCommandPlan>;
	public final chatWidgetStatusCard:Null<TuiSmokeStatusCardPlan>;
	public final chatWidgetInterruptQuit:Null<TuiSmokeChatWidgetInterruptQuitPlan>;
	public final chatWidgetInterruptedRestore:Null<TuiSmokeChatWidgetInterruptedRestorePlan>;
	public final sideConversation:Null<TuiSmokeSideConversationPlan>;
	public final clearArchive:Null<TuiSmokeClearArchivePlan>;
	public final sessionArchiveCommand:Null<TuiSmokeSessionArchiveCommandPlan>;
	public final resumeFork:Null<TuiSmokeResumeForkPlan>;
	public final terminalTitle:Null<TuiSmokeTerminalTitlePlan>;
	public final browserOpen:Null<TuiSmokeBrowserOpenPlan>;
	public final desktopThread:Null<TuiSmokeDesktopThreadPlan>;
	public final terminalVisualization:Null<TuiSmokeTerminalVisualizationPlan>;
	public final agentStatus:Null<TuiSmokeAgentStatusPlan>;
	public final agentNavigation:Null<TuiSmokeAgentNavigationPlan>;
	public final loadedThreads:Null<TuiSmokeLoadedThreadsPlan>;
	public final desktopNotification:Null<TuiSmokeDesktopNotificationPlan>;
	public final terminalHyperlink:Null<TuiSmokeTerminalHyperlinkPlan>;
	public final terminalPalette:Null<TuiSmokeTerminalPalettePlan>;
	public final terminalStartupProbe:Null<TuiSmokeTerminalStartupProbePlan>;
	public final clipboardCopy:Null<TuiSmokeClipboardCopyPlan>;
	public final clipboardPaste:Null<TuiSmokeClipboardPastePlan>;
}
