package codexhx.runtime.tui.smoke;

typedef TuiSmokeResumeForkActionFields = {
	final kind:TuiSmokeResumeForkActionKind;
	final action:String;
	final source:String;
	final context:String;
	final selection:String;
	final idOrName:String;
	final threadId:String;
	final parentThreadId:String;
	final childThreadId:String;
	final targetLabel:String;
	final targetPath:String;
	final failureCode:String;
	final errorMessage:String;
	final pageSize:Int;
	final loadedRows:Int;
	final turnCount:Int;
	final altScreenEntered:Bool;
	final altScreenExited:Bool;
	final pickerStarted:Bool;
	final showAll:Bool;
	final includeNonInteractive:Bool;
	final selected:Bool;
	final lookupRequested:Bool;
	final lookupSucceeded:Bool;
	final threadReadRequested:Bool;
	final waitForInitialSession:Bool;
	final activeEventsAllowed:Bool;
	final pausedGoalPromptEligible:Bool;
	final sameThreadActive:Bool;
	final ignored:Bool;
	final infoInserted:Bool;
	final configReloaded:Bool;
	final cwdResolved:Bool;
	final configRebuilt:Bool;
	final remoteWorkspace:Bool;
	final runtimePolicyApplied:Bool;
	final resumeRequested:Bool;
	final resumeSucceeded:Bool;
	final forkRequested:Bool;
	final forkSucceeded:Bool;
	final currentThreadShutdown:Bool;
	final chatWidgetReplaced:Bool;
	final primaryThreadEnqueued:Bool;
	final subagentsBackfilled:Bool;
	final notificationSettingsUpdated:Bool;
	final fileSearchDirUpdated:Bool;
	final summaryInserted:Bool;
	final frameScheduled:Bool;
	final appServerStarted:Bool;
	final appServerMutationRequested:Bool;
	final initialUserMessageSubmitted:Bool;
	final errorInserted:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noFilesystemMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeResumeForkAction {
	@:recordDefault(TuiSmokeResumeForkActionKind.Unknown)
	public final kind:TuiSmokeResumeForkActionKind;
	public final action:String;
	public final source:String;
	public final context:String;
	public final selection:String;
	public final idOrName:String;
	public final threadId:String;
	public final parentThreadId:String;
	public final childThreadId:String;
	public final targetLabel:String;
	public final targetPath:String;
	public final failureCode:String;
	public final errorMessage:String;
	public final pageSize:Int;
	public final loadedRows:Int;
	public final turnCount:Int;
	public final altScreenEntered:Bool;
	public final altScreenExited:Bool;
	public final pickerStarted:Bool;
	public final showAll:Bool;
	public final includeNonInteractive:Bool;
	public final selected:Bool;
	public final lookupRequested:Bool;
	public final lookupSucceeded:Bool;
	public final threadReadRequested:Bool;
	public final waitForInitialSession:Bool;
	public final activeEventsAllowed:Bool;
	public final pausedGoalPromptEligible:Bool;
	public final sameThreadActive:Bool;
	public final ignored:Bool;
	public final infoInserted:Bool;
	public final configReloaded:Bool;
	public final cwdResolved:Bool;
	public final configRebuilt:Bool;
	public final remoteWorkspace:Bool;
	public final runtimePolicyApplied:Bool;
	public final resumeRequested:Bool;
	public final resumeSucceeded:Bool;
	public final forkRequested:Bool;
	public final forkSucceeded:Bool;
	public final currentThreadShutdown:Bool;
	public final chatWidgetReplaced:Bool;
	public final primaryThreadEnqueued:Bool;
	public final subagentsBackfilled:Bool;
	public final notificationSettingsUpdated:Bool;
	public final fileSearchDirUpdated:Bool;
	public final summaryInserted:Bool;
	public final frameScheduled:Bool;
	public final appServerStarted:Bool;
	public final appServerMutationRequested:Bool;
	public final initialUserMessageSubmitted:Bool;
	public final errorInserted:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noFilesystemMutation:Bool;
	public final unsupportedRejected:Bool;
}
