package codexhx.runtime.tui.smoke;

typedef TuiSmokeRawOutputRenderActionFields = {
	final kind:TuiSmokeRawOutputRenderActionKind;
	final source:String;
	final cellKind:String;
	final renderMode:String;
	final status:String;
	final command:String;
	final toolName:String;
	final notice:String;
	final slashCommand:String;
	final failureCode:String;
	final width:Int;
	final previousWidth:Int;
	final displayLines:Int;
	final rawLines:Int;
	final transcriptLines:Int;
	final copyLines:Int;
	final visibleLines:Int;
	final hiddenLines:Int;
	final revisionBefore:Int;
	final revisionAfter:Int;
	final rawOutputBefore:Bool;
	final rawOutputAfter:Bool;
	final configUpdated:Bool;
	final noticeInserted:Bool;
	final statusVisible:Bool;
	final richMode:Bool;
	final rawMode:Bool;
	final hyperlinkAnnotated:Bool;
	final plainSelection:Bool;
	final transcriptPreserved:Bool;
	final copyPreserved:Bool;
	final commandGrouped:Bool;
	final stdoutVisible:Bool;
	final stderrVisible:Bool;
	final toolExtraImageCell:Bool;
	final activeRevisionBumped:Bool;
	final activeTailSynced:Bool;
	final renderModePropagated:Bool;
	final redrawRequested:Bool;
	final rawEventEmitted:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final noAppServerMutation:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeRawOutputRenderAction {
	public final kind:TuiSmokeRawOutputRenderActionKind;
	public final source:String;
	public final cellKind:String;
	public final renderMode:String;
	public final status:String;
	public final command:String;
	public final toolName:String;
	public final notice:String;
	public final slashCommand:String;
	public final failureCode:String;
	public final width:Int;
	public final previousWidth:Int;
	public final displayLines:Int;
	public final rawLines:Int;
	public final transcriptLines:Int;
	public final copyLines:Int;
	public final visibleLines:Int;
	public final hiddenLines:Int;
	public final revisionBefore:Int;
	public final revisionAfter:Int;
	public final rawOutputBefore:Bool;
	public final rawOutputAfter:Bool;
	public final configUpdated:Bool;
	public final noticeInserted:Bool;
	public final statusVisible:Bool;
	public final richMode:Bool;
	public final rawMode:Bool;
	public final hyperlinkAnnotated:Bool;
	public final plainSelection:Bool;
	public final transcriptPreserved:Bool;
	public final copyPreserved:Bool;
	public final commandGrouped:Bool;
	public final stdoutVisible:Bool;
	public final stderrVisible:Bool;
	public final toolExtraImageCell:Bool;
	public final activeRevisionBumped:Bool;
	public final activeTailSynced:Bool;
	public final renderModePropagated:Bool;
	public final redrawRequested:Bool;
	public final rawEventEmitted:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final noAppServerMutation:Bool;
	public final unsupportedRejected:Bool;
}
