package codexhx.runtime.tui.smoke;

typedef TuiSmokeChatWidgetStreamLifecycleActionFields = {
	final kind:TuiSmokeChatWidgetStreamLifecycleActionKind;
	final interruptKind:String;
	final finishReason:String;
	final failureCode:String;
	final delta:String;
	final queuedInterruptsBefore:Int;
	final queuedInterruptsAfter:Int;
	final queuedLinesBefore:Int;
	final queuedLinesAfter:Int;
	final committedCells:Int;
	final activeStreamControllerBefore:Bool;
	final activeStreamControllerAfter:Bool;
	final planStreamControllerBefore:Bool;
	final planStreamControllerAfter:Bool;
	final activeTailBefore:Bool;
	final activeTailAfter:Bool;
	final taskCompletePendingBefore:Bool;
	final taskCompletePendingAfter:Bool;
	final taskRunningBefore:Bool;
	final taskRunningAfter:Bool;
	final statusHidden:Bool;
	final statusPreserved:Bool;
	final pendingStatusRestoreBefore:Bool;
	final pendingStatusRestoreAfter:Bool;
	final interruptQueued:Bool;
	final interruptHandled:Bool;
	final fifoPreserved:Bool;
	final flushedInterrupts:Int;
	final startCommitAnimation:Bool;
	final stopCommitAnimation:Bool;
	final catchUpTick:Bool;
	final adaptiveChunkingReset:Bool;
	final runningCommandsCleared:Bool;
	final suppressedExecCleared:Bool;
	final unifiedWaitCleared:Bool;
	final cancelEditCleared:Bool;
	final rateLimitPromptChecked:Bool;
	final taskStateUpdated:Bool;
	final statusSurfacesRefreshed:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

@:build(codexhx.macros.FieldRecordConstructor.build())
class TuiSmokeChatWidgetStreamLifecycleAction {
	public final kind:TuiSmokeChatWidgetStreamLifecycleActionKind;
	public final interruptKind:String;
	public final finishReason:String;
	public final failureCode:String;
	public final delta:String;
	public final queuedInterruptsBefore:Int;
	public final queuedInterruptsAfter:Int;
	public final queuedLinesBefore:Int;
	public final queuedLinesAfter:Int;
	public final committedCells:Int;
	public final activeStreamControllerBefore:Bool;
	public final activeStreamControllerAfter:Bool;
	public final planStreamControllerBefore:Bool;
	public final planStreamControllerAfter:Bool;
	public final activeTailBefore:Bool;
	public final activeTailAfter:Bool;
	public final taskCompletePendingBefore:Bool;
	public final taskCompletePendingAfter:Bool;
	public final taskRunningBefore:Bool;
	public final taskRunningAfter:Bool;
	public final statusHidden:Bool;
	public final statusPreserved:Bool;
	public final pendingStatusRestoreBefore:Bool;
	public final pendingStatusRestoreAfter:Bool;
	public final interruptQueued:Bool;
	public final interruptHandled:Bool;
	public final fifoPreserved:Bool;
	public final flushedInterrupts:Int;
	public final startCommitAnimation:Bool;
	public final stopCommitAnimation:Bool;
	public final catchUpTick:Bool;
	public final adaptiveChunkingReset:Bool;
	public final runningCommandsCleared:Bool;
	public final suppressedExecCleared:Bool;
	public final unifiedWaitCleared:Bool;
	public final cancelEditCleared:Bool;
	public final rateLimitPromptChecked:Bool;
	public final taskStateUpdated:Bool;
	public final statusSurfacesRefreshed:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;

}
