package codexhx.runtime.tui.smoke;

typedef TuiSmokeChatWidgetInterruptQuitActionFields = {
	final kind:TuiSmokeChatWidgetInterruptQuitActionKind;
	final key:String;
	final route:String;
	final exitMode:String;
	final failureCode:String;
	final doublePressEnabled:Bool;
	final realtimeLive:Bool;
	final modalOrPopupActive:Bool;
	final bottomPaneHandled:Bool;
	final cancellableWorkActive:Bool;
	final taskRunning:Bool;
	final reviewMode:Bool;
	final composerEmpty:Bool;
	final quitShortcutActiveBefore:Bool;
	final quitShortcutActiveAfter:Bool;
	final quitShortcutKeyMatched:Bool;
	final quitShortcutHintShown:Bool;
	final quitShortcutHintCleared:Bool;
	final quitShortcutExpired:Bool;
	final interruptSubmitted:Bool;
	final interruptRestoresPrompt:Bool;
	final pendingSteersBefore:Int;
	final pendingSteersAfter:Int;
	final submitPendingSteersAfterInterrupt:Bool;
	final activeGoalPaused:Bool;
	final streamQueueCleared:Bool;
	final planStreamQueueCleared:Bool;
	final activeTailCleared:Bool;
	final cancelEditArmedBefore:Bool;
	final cancelEditArmedAfter:Bool;
	final cancelEditCleared:Bool;
	final appExitSent:Bool;
	final shutdownFeedbackShown:Bool;
	final appServerShutdownRequested:Bool;
	final pendingShutdownThreadBefore:Bool;
	final pendingShutdownThreadAfter:Bool;
	final inputDisabled:Bool;
	final requestRedraw:Bool;
	final noLiveTerminal:Bool;
	final noRatatuiRender:Bool;
	final noModelCall:Bool;
	final unsupportedRejected:Bool;
}

class TuiSmokeChatWidgetInterruptQuitAction {
	public final kind:TuiSmokeChatWidgetInterruptQuitActionKind;
	public final key:String;
	public final route:String;
	public final exitMode:String;
	public final failureCode:String;
	public final doublePressEnabled:Bool;
	public final realtimeLive:Bool;
	public final modalOrPopupActive:Bool;
	public final bottomPaneHandled:Bool;
	public final cancellableWorkActive:Bool;
	public final taskRunning:Bool;
	public final reviewMode:Bool;
	public final composerEmpty:Bool;
	public final quitShortcutActiveBefore:Bool;
	public final quitShortcutActiveAfter:Bool;
	public final quitShortcutKeyMatched:Bool;
	public final quitShortcutHintShown:Bool;
	public final quitShortcutHintCleared:Bool;
	public final quitShortcutExpired:Bool;
	public final interruptSubmitted:Bool;
	public final interruptRestoresPrompt:Bool;
	public final pendingSteersBefore:Int;
	public final pendingSteersAfter:Int;
	public final submitPendingSteersAfterInterrupt:Bool;
	public final activeGoalPaused:Bool;
	public final streamQueueCleared:Bool;
	public final planStreamQueueCleared:Bool;
	public final activeTailCleared:Bool;
	public final cancelEditArmedBefore:Bool;
	public final cancelEditArmedAfter:Bool;
	public final cancelEditCleared:Bool;
	public final appExitSent:Bool;
	public final shutdownFeedbackShown:Bool;
	public final appServerShutdownRequested:Bool;
	public final pendingShutdownThreadBefore:Bool;
	public final pendingShutdownThreadAfter:Bool;
	public final inputDisabled:Bool;
	public final requestRedraw:Bool;
	public final noLiveTerminal:Bool;
	public final noRatatuiRender:Bool;
	public final noModelCall:Bool;
	public final unsupportedRejected:Bool;

	public function new(fields:TuiSmokeChatWidgetInterruptQuitActionFields) {
		this.kind = fields.kind == null ? TuiSmokeChatWidgetInterruptQuitActionKind.Unknown : fields.kind;
		this.key = fields.key == null ? "" : fields.key;
		this.route = fields.route == null ? "" : fields.route;
		this.exitMode = fields.exitMode == null ? "" : fields.exitMode;
		this.failureCode = fields.failureCode == null ? "" : fields.failureCode;
		this.doublePressEnabled = fields.doublePressEnabled;
		this.realtimeLive = fields.realtimeLive;
		this.modalOrPopupActive = fields.modalOrPopupActive;
		this.bottomPaneHandled = fields.bottomPaneHandled;
		this.cancellableWorkActive = fields.cancellableWorkActive;
		this.taskRunning = fields.taskRunning;
		this.reviewMode = fields.reviewMode;
		this.composerEmpty = fields.composerEmpty;
		this.quitShortcutActiveBefore = fields.quitShortcutActiveBefore;
		this.quitShortcutActiveAfter = fields.quitShortcutActiveAfter;
		this.quitShortcutKeyMatched = fields.quitShortcutKeyMatched;
		this.quitShortcutHintShown = fields.quitShortcutHintShown;
		this.quitShortcutHintCleared = fields.quitShortcutHintCleared;
		this.quitShortcutExpired = fields.quitShortcutExpired;
		this.interruptSubmitted = fields.interruptSubmitted;
		this.interruptRestoresPrompt = fields.interruptRestoresPrompt;
		this.pendingSteersBefore = fields.pendingSteersBefore;
		this.pendingSteersAfter = fields.pendingSteersAfter;
		this.submitPendingSteersAfterInterrupt = fields.submitPendingSteersAfterInterrupt;
		this.activeGoalPaused = fields.activeGoalPaused;
		this.streamQueueCleared = fields.streamQueueCleared;
		this.planStreamQueueCleared = fields.planStreamQueueCleared;
		this.activeTailCleared = fields.activeTailCleared;
		this.cancelEditArmedBefore = fields.cancelEditArmedBefore;
		this.cancelEditArmedAfter = fields.cancelEditArmedAfter;
		this.cancelEditCleared = fields.cancelEditCleared;
		this.appExitSent = fields.appExitSent;
		this.shutdownFeedbackShown = fields.shutdownFeedbackShown;
		this.appServerShutdownRequested = fields.appServerShutdownRequested;
		this.pendingShutdownThreadBefore = fields.pendingShutdownThreadBefore;
		this.pendingShutdownThreadAfter = fields.pendingShutdownThreadAfter;
		this.inputDisabled = fields.inputDisabled;
		this.requestRedraw = fields.requestRedraw;
		this.noLiveTerminal = fields.noLiveTerminal;
		this.noRatatuiRender = fields.noRatatuiRender;
		this.noModelCall = fields.noModelCall;
		this.unsupportedRejected = fields.unsupportedRejected;
	}
}
